/**
 * Fan-style WC reliability probes — session failure modes + accuracy checks.
 * Offline only (no LLM). Run via npm run audit:wc-fan-reliability.
 *
 * Known v1 gaps (probed but not blocking):
 * - Stale live ML if BDL lags (fixtures use explicit odds; prod may drift).
 * - Tied live games lean pre-match favorite ML, not draw/double chance.
 * - No minute-aware branching (leader vs favorite uses score + open ML only).
 */

/** @typedef {{
 *   id: string,
 *   question: string,
 *   home: string,
 *   away: string,
 *   match: Record<string, unknown>,
 *   history?: Array<{ role?: string, content?: string, structured?: Record<string, unknown> }>,
 *   expectRouteLiveWinner?: boolean,
 *   expectRouteFixturePrebuilt?: boolean,
 *   forbidPatterns?: RegExp[],
 *   requirePatterns?: RegExp[],
 *   notes?: string,
 * }} WcFanReliabilityCase */

/** @type {WcFanReliabilityCase[]} */
export const WC_FAN_RELIABILITY_CASES = [
  {
    id: "live-who-wins-trailing-score",
    question: "Who wins IRN vs NZL?",
    home: "IRN",
    away: "NZL",
    match: {
      id: 16,
      homeTeam: "IRN",
      awayTeam: "NZL",
      homeScore: 0,
      awayScore: 1,
      status: "live",
      minute: 7,
      group: "G",
      odds: {
        home: { moneyline: "-130" },
        away: { moneyline: "+425" },
        draw: { moneyline: "+225" },
      },
    },
    expectRouteLiveWinner: true,
    expectRouteFixturePrebuilt: false,
    forbidPatterns: [
      /\bboth teams to advance\b/i,
      /\b1st,\s*NZL\s*2nd\b/i,
      /\bgroup[- ]stage value\b/i,
      /\bwin group\b/i,
    ],
    requirePatterns: [/\bto win\b/i, /New Zealand|NZL/i, /\+425|-\d{2,4}/],
    notes: "Session bug: live who-wins bled into group-advance futures.",
  },
  {
    id: "live-who-wins-0-0",
    question: "Who wins MEX vs RSA?",
    home: "MEX",
    away: "RSA",
    match: {
      id: 1,
      homeTeam: "MEX",
      awayTeam: "RSA",
      homeScore: 0,
      awayScore: 0,
      status: "live",
      minute: 12,
      group: "A",
      odds: {
        home: { moneyline: "-240" },
        away: { moneyline: "+650" },
        draw: { moneyline: "+320" },
      },
    },
    expectRouteLiveWinner: true,
    forbidPatterns: [/\bboth teams to advance\b/i],
    requirePatterns: [/\bto win\b/i, /Mexico|MEX/i],
    notes: "0-0 live should still be match ML, not futures.",
  },
  {
    id: "live-angle-not-winner-prebuilt",
    question: "Best live angle on IRN vs NZL right now?",
    home: "IRN",
    away: "NZL",
    match: {
      id: 16,
      homeTeam: "IRN",
      awayTeam: "NZL",
      homeScore: 0,
      awayScore: 1,
      status: "live",
      group: "G",
    },
    expectRouteLiveWinner: false,
    expectRouteFixturePrebuilt: false,
    notes: "Live-angle stays off deterministic winner prebuilt (LLM / match intel path).",
  },
  {
    id: "pre-match-who-wins-still-prebuilt",
    question: "Who wins USA vs PAR?",
    home: "USA",
    away: "PAR",
    match: {
      id: "wc-promo-usa-par",
      homeTeam: "USA",
      awayTeam: "PAR",
      homeScore: null,
      awayScore: null,
      status: "NS",
      group: "D",
      odds: {
        home: { moneyline: "+110" },
        away: { moneyline: "+285" },
        draw: { moneyline: "+240" },
      },
    },
    expectRouteLiveWinner: false,
    expectRouteFixturePrebuilt: true,
    forbidPatterns: [/\bboth teams to advance\b/i],
    requirePatterns: [/\bto win\b|Under|Over/i],
    notes: "Pre-kickoff who-wins should still hit fixture prebuilt, not live winner path.",
  },
  {
    id: "live-best-bet-moneyline",
    question: "Best bet on BEL vs EGY if I only know the moneyline?",
    home: "BEL",
    away: "EGY",
    match: {
      id: 14,
      homeTeam: "BEL",
      awayTeam: "EGY",
      homeScore: 1,
      awayScore: 1,
      status: "live",
      minute: 55,
      group: "G",
      odds: {
        home: { moneyline: "-140" },
        away: { moneyline: "+380" },
        draw: { moneyline: "+210" },
      },
    },
    expectRouteLiveWinner: true,
    forbidPatterns: [/\bboth teams to advance\b/i],
    requirePatterns: [/\bto win\b/i],
    notes: "Live moneyline-best-bet phrasing must stay on this fixture's ML.",
  },
  {
    id: "live-who-wins-follow-up-in-thread",
    question: "Who wins?",
    home: "IRN",
    away: "NZL",
    history: [
      { role: "user", content: "Best live angle on IRN vs NZL right now?" },
      {
        role: "assistant",
        structured: {
          callType: "matchup",
          fixtureHome: "IRN",
          fixtureAway: "NZL",
          call: "Iran +180 to win",
          lean: "Iran +180 to win",
        },
      },
    ],
    match: {
      id: 16,
      homeTeam: "IRN",
      awayTeam: "NZL",
      homeScore: 0,
      awayScore: 1,
      status: "live",
      minute: 12,
      group: "G",
      odds: {
        home: { moneyline: "-130" },
        away: { moneyline: "+425" },
        draw: { moneyline: "+225" },
      },
    },
    expectRouteLiveWinner: true,
    forbidPatterns: [/\bboth teams to advance\b/i],
    requirePatterns: [/\bto win\b/i, /New Zealand|NZL/i],
    notes: "Mid-thread who-wins must inherit fixture from history, not bleed to LLM futures.",
  },
  {
    id: "live-tied-uses-prematch-favorite-v1",
    question: "Best bet on BEL vs EGY if I only know the moneyline?",
    home: "BEL",
    away: "EGY",
    match: {
      id: 14,
      homeTeam: "BEL",
      awayTeam: "EGY",
      homeScore: 1,
      awayScore: 1,
      status: "live",
      minute: 70,
      group: "G",
      odds: {
        home: { moneyline: "-140" },
        away: { moneyline: "+380" },
        draw: { moneyline: "+210" },
      },
    },
    expectRouteLiveWinner: true,
    forbidPatterns: [/\bboth teams to advance\b/i, /\bdraw\b/i],
    requirePatterns: [/Belgium.*-140 to win/i],
    notes: "v1 contract: tied live leans pre-match ML favorite, not draw/double chance.",
  },
];
