export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.status(200).json({
    surfaces: {
      "tennis_atp_miami_open": { name: "Miami Open", surface: "Hard", speed: "Medium-Fast", note: "Miami's hard courts play slightly slower than most hard court events. Heavy topspin and baseline consistency are rewarded. Big servers still have an edge but rallies run longer than at the US Open." },
      "tennis_wta_miami_open": { name: "Miami Open", surface: "Hard", speed: "Medium-Fast", note: "Miami hard courts favor aggressive baseliners. Sabalenka just won Indian Wells and arrives as the clear favorite at 35.4% per Tennis Abstract simulations. Slightly slower conditions than the US Open benefit topspin baseliners." },
      "tennis_atp_french_open": { name: "French Open", surface: "Clay", speed: "Slow", note: "Roland Garros clay neutralizes big servers and rewards endurance and topspin. The two-week grind tests fitness more than any other Slam. Alcaraz has won here twice and Sinner is improving rapidly on clay." },
      "tennis_wta_french_open": { name: "French Open", surface: "Clay", speed: "Slow", note: "Clay at Roland Garros rewards heavy topspin, patience, and elite fitness. Swiatek has dominated this event. Points are longer, serve advantages shrink, and fitness is the deciding factor deep in draws." },
      "tennis_atp_wimbledon": { name: "Wimbledon", surface: "Grass", speed: "Fast", note: "Wimbledon grass is the fastest major surface. Big servers dominate early rounds, points are short, and net rushers have a natural advantage. Alcaraz won here in 2023 and 2024 before losing to Sinner in the 2025 final." },
      "tennis_wta_wimbledon": { name: "Wimbledon", surface: "Grass", speed: "Fast", note: "Grass at Wimbledon rewards flat hitting, serve power, and net aggression. Rybakina won here in 2022 and is the standout performer on this surface. Clay court specialists frequently exit early." },
      "tennis_atp_us_open": { name: "US Open", surface: "Hard", speed: "Medium", note: "US Open DecoTurf plays faster than Miami. Night conditions with cool air amplify serve speed. Alcaraz won the 2025 US Open, beating Sinner in the final." },
      "tennis_wta_us_open": { name: "US Open", surface: "Hard", speed: "Medium", note: "Flushing Meadows rewards aggression and power. Gauff won the 2023 US Open on this surface. The fast DecoTurf suits players with big serves and flat groundstrokes." },
    },
    atp: {
      // Source: ATP Tour Infosys Win/Loss Index, Tennis Abstract Elo ratings + Return Leaders (March 16, 2026)
      // Return stats: RPW = Return Points Won %, Brk% = Break %, Tour avg: RPW 36.7%, Brk% 21.3%
      "Alcaraz": {
        eloRank: 1, elo: 2290,
        hElo: 2216.8, hEloRank: 2, cElo: 2225.2, cEloRank: 1, gElo: 2148.3, gEloRank: 1, peakElo: 2308.5, peakMonth: "2026-03",
        yEloRank: 1,  yElo2026: 2123.9, record2026: "16-1 — Won Australian Open, unbeaten until IW final. #1 in-season form on tour.",
        record: "72-7 (91.1%) last 52 weeks",
        style: "All-court attacker",
        strengths: "Drop shots, net presence, elite athleticism on all surfaces",
        serveStats: "Hold 88.5%, Ace 7.2%, DF 3.1%",
        returnStats: "RPW 41.6%, Break rate 30.7% — 45% above tour average of 21.3%",
        bpStats: "Break point conversion 43.5%, Save rate 66.9%",
        overallStats: "Dominance Ratio 1.31, TPW 54.5%, Tiebreak 61.8%",
        h2h: "vs Sinner 11-6 · vs Djokovic 4-5 · vs Zverev 6-6 · vs Medvedev 6-2 · vs Fritz 5-1 · vs De Minaur 5-0 · vs Shelton 3-0 (source: Tennis Abstract)",
        fullNote: "The most complete statistical profile on tour. 91.1% win rate, DR 1.31 means he wins 31% more points than he loses. Elite on both serve and return. Converts 43.5% of break chances and saves 66.9% of break points faced.",
        hardRecord: "158-42 career hard court record (79%). Currently on a 34-match outdoor hard court winning streak — third best in history behind Federer and Connors.",
        miamiNote: "Won Miami in 2022 and 2023. Arrives unbeaten in 2026 (16-0) after winning the Australian Open. His combination of movement, variety, and shot-making makes him the most complete hard court player on tour right now alongside Sinner.",
        surfaceNote: { hard: "Won Australian Open 2026, US Open 2025, Miami Open 2022 and 2023. 79% career hard court win rate.", clay: "Won Roland Garros 2024 and 2025. Clay is his strongest surface historically.", grass: "Won Wimbledon 2023 and 2024. Lost 2025 Wimbledon final to Sinner." }
      },
      "Sinner": {
        eloRank: 2, elo: 2285,
        hElo: 2238.2, hEloRank: 1, cElo: 2149.6, cEloRank: 2, gElo: 2070.7, gEloRank: 2, peakElo: 2329.6, peakMonth: "2025-01",
        yEloRank: 3,  yElo2026: 2094.7, record2026: "13-2 — Won Indian Wells. Fewer matches than Alcaraz/Medvedev but quality arguably #1.",
        record: "64-8 (88.9%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Devastating backhand, elite return game, exceptional fitness and mental composure",
        serveStats: "Hold 91.8% — best on tour, Ace 10.2%, DF 1.9% — lowest on tour",
        returnStats: "RPW 42.2%, Break rate 32.1% — #1 on tour, 50% above tour average",
        bpStats: "Break point conversion 43.6%, Save rate 72.4% — best on tour",
        overallStats: "Dominance Ratio 1.49 — best on tour, TPW 56.2%, Tiebreak 81.0% — best on tour",
        h2h: "vs Alcaraz 6-11 · vs Djokovic 4-6 · vs Zverev 6-4 · vs Medvedev 8-7 · vs De Minaur 13-0 · vs Fritz 4-1 · vs Shelton 8-1 (source: Tennis Abstract)",
        fullNote: "DR 1.49 is the best on tour — wins 49% more points than he loses. Tour-leading hold (91.8%), break rate (32.1%), BP save rate (72.4%), and 81% tiebreak win rate. His DF rate (1.9%) is the lowest in the top 50. Statistically the most dominant player right now.",
        hardRecord: "234-54 career hard court record (81.3%) — second among all active players. Just completed the full hard court Masters set by winning Indian Wells.",
        miamiNote: "Arrives as Miami favorite at 41.2% per Tennis Abstract after winning Indian Wells. Now targeting the Sunshine Double — Indian Wells and Miami back to back. Hard courts are where he is most dominant.",
        surfaceNote: { hard: "81.3% career hard court win rate. Won Australian Open 2024 and 2025, Indian Wells 2026, ATP Finals 2024 and 2025. Has now won every major hard court event.", clay: "Strong but not dominant on clay — lost French Open final to Alcaraz in 2025.", grass: "Won Wimbledon 2025. Still developing his grass game but improving rapidly." }
      },
      "Djokovic": {
        eloRank: 3, elo: 2100,
        hElo: 2051.8, hEloRank: 3, cElo: 2002.2, cEloRank: 4, gElo: 1955.0, gEloRank: 3, peakElo: 2463.2, peakMonth: "2016-05",
        yEloRank: 13, yElo2026: 1895.9, record2026: "7-2 — Limited schedule. yElo rank 13 reflects small sample, not true level.",
        record: "39-9 (81.3%) last 52 weeks",
        style: "Counter-punching baseliner",
        strengths: "Return of serve, defensive retrieval, mental toughness, all-surface adaptability",
        serveStats: "Hold 87.8%, Ace 9.5%, DF 2.7%",
        returnStats: "RPW 39.6%, Break rate 26.4% — well above tour average",
        bpStats: "Break point conversion 41.8%, Save rate 64.9%",
        overallStats: "Dominance Ratio 1.30, TPW 54.1%, Tiebreak 52.4% — near coin-flip, notable decline",
        h2h: "vs Alcaraz 5-4 · vs Sinner 6-4 · vs Zverev 9-5 · vs Medvedev 10-5 · vs Fritz 8-2 (source: Tennis Abstract)",
        fullNote: "Still elite at 38. DR 1.30, solid hold and break rates. Only weakness: tiebreaks at 52.4% — almost exactly coin-flip, a notable departure from his historically dominant tiebreak record.",
        hardRecord: "Career 81%+ hard court win rate. The all-time record holder at most major hard court events.",
        miamiNote: "All-time Miami record is exceptional but at 38 he now selects his schedule carefully. When motivated he remains the best defensive player on tour and a threat to go deep in any draw.",
        surfaceNote: { hard: "Greatest hard court player in history — 10 Australian Opens, 4 US Opens.", clay: "Exceptional on clay — Roland Garros champion multiple times.", grass: "Greatest Wimbledon champion — 7 titles." }
      },
      "Zverev": {
        eloRank: 4, elo: 2060,
        hElo: 2016.5, hEloRank: 4, cElo: 2002.8, cEloRank: 3, gElo: 1885.1, gEloRank: 6, peakElo: 2176.5, peakMonth: "2022-01",
        yEloRank: 4,  yElo2026: 2000.9, record2026: "11-4 — Solid but clear drop from top 3.",
        record: "56-24 (70.0%) last 52 weeks",
        style: "Power baseliner",
        strengths: "Serve, forehand, clay court movement",
        serveStats: "Hold 87.9%, Ace 10.6%, DF 2.2%",
        returnStats: "RPW 36.8%, Break rate 21.3% — exactly tour average, no return edge",
        bpStats: "Break point conversion 41.8%, Save rate 63.1%",
        overallStats: "Dominance Ratio 1.18, TPW 52.3%, Tiebreak 62.2%",
        h2h: "vs Alcaraz 6-6 · vs Sinner 4-6 · vs Djokovic 5-9 · vs Medvedev 8-6 · vs De Minaur 3-8 (source: Tennis Abstract)",
        fullNote: "Good serve (87.9% hold) but return game is exactly tour average (21.3% break rate). His 70% win rate reflects the gap. When his serve is broken he has no return weapon to compensate.",
        hardRecord: "Solid hard court record but inconsistent at the top level.",
        miamiNote: "Has not won Miami despite his ranking. His game is better suited to clay and he tends to lose to elite opponents on hard courts in close matches.",
        surfaceNote: { hard: "Capable on hard but not dominant — better on clay.", clay: "Roland Garros finalist multiple times — clay is his best surface.", grass: "Below his ranking at Wimbledon." }
      },
      "Medvedev": {
        eloRank: 5, elo: 2030,
        hElo: 1994.7, hEloRank: 5, cElo: 1929.5, cEloRank: 7, gElo: 1893.9, gEloRank: 5, peakElo: 2201.2, peakMonth: "2022-01",
        yEloRank: 2,  yElo2026: 2096.6, record2026: "18-4 — Most wins of any top player in 2026. Lost IW final to Sinner. Best form in years.",
        record: "47-21 (69.1%) last 52 weeks",
        style: "Defensive baseliner",
        strengths: "Return game, flat low-bouncing groundstrokes, mental resilience in long matches",
        serveStats: "Hold 84.2% — weakest in top 10, Ace 11.2%, DF 5.7% — highest in top 10",
        returnStats: "RPW 40.1%, Break rate 27.5% — 4th on tour, well above average",
        bpStats: "Break point conversion 40.3%, Save rate 62.4% — below top 10 average",
        overallStats: "Dominance Ratio 1.17, TPW 52.5%, Tiebreak 41.9% — worst in top 10",
        h2h: "vs Alcaraz 2-6 · vs Sinner 7-8 · vs Djokovic 5-10 · vs Zverev 6-8 · vs Fritz 8-4 (source: Tennis Abstract)",
        fullNote: "Elite return game (4th on tour) but serve is a liability — 5.7% DF rate highest in top 10, 84.2% hold weakest. His 41.9% tiebreak win rate is worst in the top 10 — he consistently loses close sets, explaining why he cannot convert form into titles.",
        hardRecord: "US Open champion 2021. Multiple Australian Open finalist. Hard courts are clearly his best surface by a wide margin.",
        miamiNote: "Just lost the Indian Wells final to Sinner in two tiebreaks. Hard courts suit his flat game well and he arrives in good form. His return stats rank among the best on tour.",
        surfaceNote: { hard: "Elite on hard — US Open champion, two-time Australian Open finalist.", clay: "Noticeably weaker on clay — tends to lose to lower-ranked players at Roland Garros.", grass: "Below par on grass, tends to exit early at Wimbledon." }
      },
      "De Minaur": {
        eloRank: 6, elo: 2024,
        hElo: 1974.8, hEloRank: 6, cElo: 1908.9, cEloRank: 8, gElo: 1847.7, gEloRank: 8, peakElo: 2053.1, peakMonth: "2024-06",
        yEloRank: 6,  yElo2026: 1958.2, record2026: "12-4 — Consistent elite form to start 2026.",
        record: "53-23 (69.7%) last 52 weeks",
        style: "Counter-punching speedster",
        strengths: "Elite footwork, defensive retrieval, slice backhand, elite fitness",
        serveStats: "Hold 84.9%, Ace 5.8% — lowest ace rate in top 10 (placement over power), DF 3.2%",
        returnStats: "RPW 40.4%, Break rate 27.4% — 3rd on tour, ahead of Medvedev",
        bpStats: "Break point conversion 43.0%, Save rate 65.1%",
        overallStats: "Dominance Ratio 1.20, TPW 53.0%, Tiebreak 60.0%",
        h2h: "vs Sinner 0-13 · vs Alcaraz 0-5 · vs Zverev 8-3 · vs Medvedev 3-5 · vs Fritz 6-3 (source: Tennis Abstract)",
        fullNote: "Return ranks 3rd on tour (ahead of Medvedev). Lowest ace rate in top 10 — wins serve points through placement not power. Well-rounded game with no obvious single weakness. His elite speed allows him to get into rallies no one else can.",
        hardRecord: "Consistently performs above his seed at hard court events due to his speed and counter-punching.",
        miamiNote: "A legitimate dangerous floater in this draw. His elite speed neutralizes power players and he has the fitness to outlast anyone in a grinding match on hard courts.",
        surfaceNote: { hard: "His best surface — elite speed is maximized on hard.", clay: "Competitive but not elite on clay.", grass: "Good on grass — his speed translates well." }
      },
      "Auger-Aliassime": {
        eloRank: 7, elo: 1999,
        hElo: 1960.0, hEloRank: 7, cElo: 1870.2, cEloRank: 13, gElo: 1800.6, gEloRank: 11, peakElo: 2062.7, peakMonth: "2022-10",
        yEloRank: 7,  yElo2026: 1955.5, record2026: "14-5 — Strong volume, confirming hard court form is real.",
        record: "48-23 (67.6%) last 52 weeks",
        style: "Serve-and-volley attacker",
        strengths: "Serve, net play, indoor and outdoor hard court game",
        serveStats: "Hold 87.4%, Ace 13.8% — 3rd highest on tour, DF 4.0%",
        returnStats: "RPW 36.0%, Break rate 18.5% — below tour average of 21.3%",
        bpStats: "Break point conversion 35.0% — below average, Save rate 67.6%",
        overallStats: "Dominance Ratio 1.18, TPW 52.0%, Tiebreak 64.3%",
        h2h: "vs Alcaraz 3-5 · vs Sinner 2-4 · vs Medvedev 4-6 · vs Zverev 3-6 (source: Tennis Abstract)",
        fullNote: "Serve-dominant — 3rd highest ace rate on tour (13.8%), strong hold rate (87.4%). Return is the clear gap: 18.5% break rate is below tour average. His path to winning depends entirely on his serve. Strong in tiebreaks (64.3%) which helps compensate.",
        hardRecord: "Strong hard court results, particularly indoor. Tennis Abstract notes his exceptional hard court form.",
        miamiNote: "His serve-and-volley style works well on Miami's hard courts. A dangerous floater who can upset higher-ranked opponents if his serve is firing.",
        surfaceNote: { hard: "Strong on hard courts — his serve and net game are most effective here.", clay: "Below his ranking on clay.", grass: "Natural grass court player." }
      },
      "Shelton": {
        eloRank: 8, elo: 1996,
        hElo: 1952.3, hEloRank: 8, cElo: 1864.3, cEloRank: 14, gElo: 1813.6, gEloRank: 10, peakElo: 2024.4, peakMonth: "2025-08",
        yEloRank: 5,  yElo2026: 1966.4, record2026: "11-3 — Best season form of his career. #5 yElo is a genuine breakthrough.",
        record: "41-22 (65.1%) last 52 weeks",
        style: "Power server, aggressive attacker",
        strengths: "Left-handed serve, aggressive baseline game, net presence",
        serveStats: "Hold 87.8%, Ace 13.0%, DF 3.7%",
        returnStats: "RPW 33.3%, Break rate 16.3% — second weakest in top 10",
        bpStats: "Break point conversion 40.1%, Save rate 68.3%",
        overallStats: "Dominance Ratio 1.07 — lowest in top 10, TPW 51.1%, Tiebreak 58.1%",
        h2h: "vs Sinner 1-8 · vs Alcaraz 0-3 · vs Medvedev 3-4 · vs Fritz 5-3 (source: Tennis Abstract)",
        fullNote: "DR 1.07 is the lowest in the top 10 — barely wins more points than he loses overall. His serve is elite but his return (16.3% break rate) is the second weakest in the top 10. Against Sinner or Alcaraz's return games his serve will face maximum pressure.",
        hardRecord: "Most of his best results have come on hard courts. The left-handed serve creates unusual angles.",
        miamiNote: "Dangerous on US hard courts. His left-handed serve creates havoc and his aggressive style suits Miami's medium-fast surface. Always a threat to go deep at home events.",
        surfaceNote: { hard: "Most effective on hard courts — his serve dominates.", clay: "Less effective on clay.", grass: "Solid on grass — his serve is even more effective." }
      },
      "Fritz": {
        eloRank: 9, elo: 1983,
        hElo: 1926.1, hEloRank: 10, cElo: 1874.1, cEloRank: 12, gElo: 1915.8, gEloRank: 4, peakElo: 2070.2, peakMonth: "2025-09",
        yEloRank: 22, yElo2026: 1838.8, record2026: "10-7 — Underperforming in 2026. yElo rank 22 is well below his career Elo ranking.",
        record: "53-25 (67.9%) last 52 weeks",
        style: "Big server, aggressive baseliner",
        strengths: "Serve power, forehand, US hard court comfort",
        serveStats: "Hold 89.2% — best in top 10, Ace 15.8% — highest on tour, DF 2.4%",
        returnStats: "RPW 34.4%, Break rate 15.6% — weakest returner in top 10",
        bpStats: "Break point conversion 34.1% — lowest in top 10, Save rate 68.1%",
        overallStats: "Dominance Ratio 1.16, TPW 52.0%, Tiebreak 59.6%",
        h2h: "vs Sinner 1-4 · vs Alcaraz 1-5 · vs Medvedev 4-8 · vs Zverev 3-6 · vs De Minaur 3-6 (source: Tennis Abstract)",
        fullNote: "Highest ace rate on tour (15.8%), best hold rate in top 10 (89.2%) — but worst break rate (15.6%) and lowest BP conversion (34.1%). Entirely one-sided: dominant server, weak returner. Against Sinner's 91.8% hold rate he will generate almost no break chances.",
        hardRecord: "Strong US hard court performer. Has won ATP titles on hard and is comfortable in these conditions.",
        miamiNote: "A legitimate title threat on US hard courts. His powerful serve and forehand can overpower opponents. Comfortable playing in front of home crowds.",
        surfaceNote: { hard: "Strong on US hard courts — this is where he wins titles.", clay: "Below his ranking on clay.", grass: "Solid on grass." }
      },
      "Musetti": {
        eloRank: 10, elo: 1979,
        hElo: 1908.7, hEloRank: 12, cElo: 1984.0, cEloRank: 5, gElo: 1855.6, gEloRank: 7, peakElo: 2050.5, peakMonth: "2025-05",
        yEloRank: 17, yElo2026: 1865.3, record2026: "7-3 — Modest 2026 form, confirming hard courts are not his best surface.",
        record: "47-22 (68.1%) last 52 weeks",
        style: "One-handed backhand all-court player",
        strengths: "One-handed backhand, clay court movement, variety and drop shots",
        serveStats: "Hold 83.4% — lowest in top 10, Ace 6.1%, DF 2.4%",
        returnStats: "RPW 38.8%, Break rate 25.0% — above tour average for a clay specialist",
        bpStats: "Break point conversion 39.2%, Save rate 62.1% — lowest in top 10",
        overallStats: "Dominance Ratio 1.14, TPW 52.1%, Tiebreak 45.5% — second worst in top 10",
        h2h: "vs Alcaraz 1-8 · vs Sinner 0-3 · vs Zverev 3-2 · vs De Minaur 2-3 (source: Tennis Abstract)",
        fullNote: "Strong return for a clay specialist (25% break rate, above tour avg) but his serve is weak — 83.4% hold lowest in top 10, 62.1% BP save rate also the lowest. Gets broken often. 45.5% tiebreak rate is poor — hard courts expose him in tight sets.",
        hardRecord: "Below his ranking on hard courts — clay is strongly preferred.",
        miamiNote: "Clay specialist who tends to underperform his ranking on fast hard courts. His elegant one-handed backhand is harder to control on faster surfaces.",
        surfaceNote: { hard: "Below his ranking on hard courts.", clay: "Excellent on clay — his best surface by far.", grass: "Decent on grass." }
      },
    },
    wta: {
      // Source: Tennis Abstract Elo ratings, WTA winners/UFE leaderboard (March 16, 2026)
      // Winners/UFE ratio sourced directly from Tennis Abstract last 52 weeks data
      "Sabalenka": {
        eloRank: 1, elo: 2247,
        hElo: 2203.9, hEloRank: 1, cElo: 2142.8, cEloRank: 1, gElo: 2000.2, gEloRank: 1, peakElo: 2247.1, peakMonth: "2026-03",
        yEloRank: 1,  yElo2026: 2199.2, record2026: "17-1 — Dominant. Won Indian Wells. #1 in-season form by a wide margin.",
        record: "63-9 (87.5%) last 52 weeks",
        style: "Power baseliner",
        strengths: "Serve power, forehand aggression, hard court dominance",
        serveStats: "Hold 79.9%, Ace 6.6%, DF 3.3% — lowest DF rate among top 5",
        returnStats: "RPW 45.3%, Break rate 38.0% — above tour avg of 35.8%",
        bpStats: "Break point conversion 44.5%, Save rate 66.0% — best save rate in top 5",
        overallStats: "DR 1.22, TPW 54.0%, Tiebreak 92.3% — 24-2 record, historically extraordinary",
        h2h: "vs Swiatek 5-8 · vs Rybakina 8-7 · vs Gauff 6-6 · vs Pegula 9-3 · vs Svitolina 6-1 · vs Anisimova 6-5 (source: Tennis Abstract)",
        fullNote: "The most complete player on the WTA tour statistically. 87.5% win rate, elite on both serve (lowest DF in top 5) and return. Her 38% break rate and 45.3% RPW are elite numbers. Just won Indian Wells and arrives as Miami favorite at 35.4%.",
        miamiNote: "Just won Indian Wells, arrives as Miami favorite at 35.4%. Her stats are elite — more winners than errors, rare for a top player. Hard courts are her domain.",
        surfaceNote: { hard: "Premier hard court force in women's tennis. Won Miami 2023, Indian Wells 2026, Australian Open 2024 and 2025.", clay: "Solid on clay but Swiatek and topspin players can neutralize her power.", grass: "Good on grass — her flat serve is devastating on fast surfaces." }
      },
      "Rybakina": {
        eloRank: 2, elo: 2163,
        hElo: 2124.3, hEloRank: 2, cElo: 2006.4, cEloRank: 4, gElo: 1915.4, gEloRank: 3, peakElo: 2176.7, peakMonth: "2026-02",
        yEloRank: 3,  yElo2026: 2124.2, record2026: "17-4 — Strong volume and quality. #3 in-season form.",
        record: "61-17 (78.2%) last 52 weeks",
        style: "Power server, flat hitter",
        strengths: "Biggest serve in women's tennis — 10.3% ace rate tops the tour, flat groundstrokes, composure",
        serveStats: "Hold 83.6% — best on tour, Ace 10.3% — highest on tour by far, DF 3.7%",
        returnStats: "RPW 42.7%, Break rate 33.0% — below tour average of 35.8%",
        bpStats: "Break point conversion 45.3%, Save rate 66.7%",
        overallStats: "DR 1.23, TPW 53.7%, Tiebreak 56.0% — near average",
        h2h: "vs Sabalenka 7-8 · vs Swiatek 6-6 · vs Gauff 1-0 · vs Pegula 4-3 (source: Tennis Abstract)",
        fullNote: "Best hold rate on tour (83.6%) and highest ace rate (10.3%) by a wide margin. Her serve is her dominant weapon. Return is slightly below tour average — her only relative weakness. Hard courts amplify her flat serve.",
        miamiNote: "Hard courts suit her flat hitting. Her serve is the most dominant weapon in women's tennis. Always a threat to win big hard court events.",
        surfaceNote: { hard: "Strong on hard — flat serve is devastating.", clay: "Less dominant on clay — topspin players slow her down.", grass: "Her best surface — Wimbledon champion 2022." }
      },
      "Swiatek": {
        eloRank: 3, elo: 2110,
        hElo: 2055.5, hEloRank: 4, cElo: 2054.3, cEloRank: 2, gElo: 1950.7, gEloRank: 2, peakElo: 2291.0, peakMonth: "2024-07",
        yEloRank: 7,  yElo2026: 1957.7, record2026: "12-5 — Significantly underperforming vs career level. #7 yElo is her weakest season start in years.",
        record: "56-17 (76.7%) last 52 weeks",
        style: "Heavy topspin baseliner",
        strengths: "Forehand topspin, consistency, mental strength, elite return game",
        serveStats: "Hold 75.1% — below tour average of 70.9% adjusted, Ace 5.6%, DF 5.1% — high",
        returnStats: "RPW 47.3%, Break rate 43.8% — #1 on tour, 22% above tour average",
        bpStats: "Break point conversion 51.2% — best on tour, Save rate 58.5% — below tour average",
        overallStats: "DR 1.23, TPW 54.3%, Tiebreak 75.0%",
        h2h: "vs Sabalenka 8-5 · vs Rybakina 6-6 · vs Gauff 11-5 · vs Pegula 6-5 · vs Anisimova 2-1 (source: Tennis Abstract)",
        fullNote: "The best returner in women's tennis — 47.3% RPW and 43.8% break rate are both #1 on tour. Her serve is actually a relative weakness (75.1% hold, high DF) which is why aggressive servers like Sabalenka and Rybakina can exploit her. She wins matches by dominating return games.",
        miamiNote: "Won Miami 2022. The slower Miami hard courts play closer to her preferred clay conditions. Dangerous but can be exposed by Sabalenka-level aggression.",
        surfaceNote: { hard: "Very strong but not untouchable — Sabalenka has her number on hard.", clay: "Greatest clay player active — Roland Garros champion 4 times.", grass: "Weaker on grass — tends to exit earlier at Wimbledon." }
      },
      "Pegula": {
        eloRank: 4, elo: 2094,
        hElo: 2056.0, hEloRank: 3, cElo: 1909.1, cEloRank: 8, gElo: 1876.9, gEloRank: 5, peakElo: 2101.6, peakMonth: "2026-03",
        yEloRank: 2,  yElo2026: 2131.5, record2026: "16-3 — BEST SEASON OF HER CAREER. #2 in-season form, ahead of Rybakina and Swiatek. Massively underrated coming into Miami.",
        record: "54-21 (72.0%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Forehand power, hard court consistency, low error rate",
        serveStats: "Hold 75.0%, Ace 4.6%, DF 3.0% — second lowest in top 5",
        returnStats: "RPW 45.1%, Break rate 38.1% — above tour average",
        bpStats: "Break point conversion 45.1%, Save rate 59.8%",
        overallStats: "DR 1.17, TPW 53.0%, Tiebreak 47.6% — below average, notable weakness",
        h2h: "vs Sabalenka 3-9 · vs Swiatek 5-6 · vs Rybakina 3-4 · vs Gauff 8-5 (source: Tennis Abstract)",
        fullNote: "Consistent and disciplined on both sides. 38.1% break rate and 45.1% RPW are both elite. Very low DF rate (3.0%) means she rarely self-destructs. Her game is not spectacular but it is extremely reliable — she beats herself very rarely.",
        miamiNote: "Hard courts are her best surface. Disciplined and consistent — she stays in rallies and relies on opponents making mistakes, which works well on slower Miami hard courts.",
        surfaceNote: { hard: "Strong on hard courts — consistently reaches deep at major hard court events.", clay: "Competitive but clay is not her peak surface.", grass: "Below her ranking on grass." }
      },
      "Gauff": {
        eloRank: 5, elo: 2074,
        hElo: 2017.0, hEloRank: 6, cElo: 2044.5, cEloRank: 3, gElo: 1842.7, gEloRank: 6, peakElo: 2155.7, peakMonth: "2024-01",
        yEloRank: 14, yElo2026: 1909.8, record2026: "11-5 — Underperforming relative to career level. #14 yElo is well below expectations.",
        record: "48-17 (73.8%) last 52 weeks",
        style: "Athletic all-court player",
        strengths: "Return game is elite, athleticism, improving serve",
        serveStats: "Hold 65.6% — weakest in top 5, Ace 3.4%, DF 10.4% — highest on tour by far",
        returnStats: "RPW 49.3%, Break rate 48.1% — both #1 on tour among top players",
        bpStats: "Break point conversion 53.1% — #2 on tour, Save rate 51.3% — worst in top 5",
        overallStats: "DR 1.16, TPW 53.3%, Tiebreak 66.7%",
        h2h: "vs Sabalenka 6-6 · vs Swiatek 5-11 · vs Rybakina 0-1 · vs Pegula 5-8 (source: Tennis Abstract)",
        fullNote: "The best return stats on tour — 49.3% RPW and 48.1% break rate are remarkable. But her serve is a serious liability: 65.6% hold rate is the weakest in the top 5 and her 10.4% DF rate is the highest on the entire tour. She gets broken constantly but also breaks constantly — her matches become return battles.",
        miamiNote: "US hard courts are her best environment. US Open champion 2023. Her return game and athleticism are elite. The lower winners ratio means she needs opponents to make mistakes — risky against Sabalenka or Rybakina.",
        surfaceNote: { hard: "Strong on US hard courts — US Open champion.", clay: "Competitive on clay but not dominant.", grass: "Tends to struggle at Wimbledon." }
      },
      "Mboko": {
        eloRank: 6, elo: 2072,
        hElo: 2037.4, hEloRank: 5, cElo: 1862.4, cEloRank: 10, gElo: 1749.6, gEloRank: 21, peakElo: 2082.1, peakMonth: "2026-03",
        yEloRank: 5,  yElo2026: 2087.4, record2026: "16-5 — Confirming her rise is real. #5 in-season form is extraordinary for a 20-year-old.",
        record: "38-15 (71.7%) last 52 weeks",
        style: "Aggressive young baseliner",
        strengths: "Power, athleticism, rising form",
        serveStats: "Hold 72.6%, Ace 6.3%, DF 7.1% — high DF rate",
        returnStats: "RPW 44.1%, Break rate 38.2% — above tour average",
        bpStats: "Break point conversion 51.8%, Save rate 55.8% — below tour average",
        overallStats: "DR 1.07, TPW 51.5%, Tiebreak 37.5% — significant weakness",
        fullNote: "A 20-year-old Canadian rising fast. 71.7% win rate at Elo rank 6 is impressive. Her 7.1% DF rate is high and will be a limiting factor against elite players. Break rate (38.2%) is above tour average which shows her return game is developing well.",
        miamiNote: "A rapidly rising Canadian at 20 years old. Her Elo of 2072 places her firmly in title contention territory. Limited Miami track record but her form in 2026 has been exceptional.",
        surfaceNote: { hard: "Most of her best results on hard courts.", clay: "Still developing on clay.", grass: "Limited grass record." }
      },
      "Anisimova": {
        eloRank: 7, elo: 2050,
        hElo: 2001.5, hEloRank: 8, cElo: 1862.0, cEloRank: 11, gElo: 1885.6, gEloRank: 4, peakElo: 2086.9, peakMonth: "2025-11",
        yEloRank: 16, yElo2026: 1903.8, record2026: "9-5 — Solid but not elite form in 2026.",
        record: "45-18 (71.4%) last 52 weeks",
        style: "Aggressive flat hitter",
        strengths: "Forehand power, flat groundstrokes, serve",
        serveStats: "Hold 73.1%, Ace 5.3%, DF 5.9% — above average DF rate",
        returnStats: "RPW 45.2%, Break rate 38.4% — above tour average",
        bpStats: "Break point conversion 47.3%, Save rate 59.1% — above average",
        overallStats: "DR 1.13, TPW 52.5%, Tiebreak 58.8%",
        h2h: "vs Sabalenka 6-5 · vs Swiatek 2-1 · vs Gauff 3-4 (source: Tennis Abstract)",
        fullNote: "Solid all-round numbers — 38.4% break rate and 45.2% RPW are both above tour average. High DF rate (5.9%) is the risk — she can lose serve unexpectedly. When on she can beat anyone; when off her DF rate derails matches.",
        miamiNote: "Dangerous draw threat with big upside and real downside risk. When she hits her spots she can beat anyone. When she is off she gifts games away.",
        surfaceNote: { hard: "Best surface — flat hitting works well.", clay: "Less consistent on clay.", grass: "Capable when hitting cleanly." }
      },
      "Svitolina": {
        eloRank: 8, elo: 2049,
        hElo: 1993.6, hEloRank: 9, cElo: 1955.7, cEloRank: 5, gElo: 1826.0, gEloRank: 7, peakElo: 2120.6, peakMonth: "2018-05",
        yEloRank: 4,  yElo2026: 2113.1, record2026: "19-4 — Most wins on the WTA tour in 2026. #4 in-season form is her best in years. Massively underrated at Miami.",
        record: "46-14 (76.7%) last 52 weeks",
        style: "Counter-punching defensive baseliner",
        strengths: "Consistency, retrieval, mental toughness, low error rate",
        serveStats: "Hold 73.9%, Ace 4.9%, DF 4.3%",
        returnStats: "RPW 46.0%, Break rate 41.3% — well above tour average",
        bpStats: "Break point conversion 52.1% — 3rd on tour, Save rate 60.5% — above average",
        overallStats: "DR 1.14, TPW 53.0%, Tiebreak 66.7%",
        h2h: "vs Sabalenka 1-6 · vs Swiatek 1-4 · vs Rybakina 1-3 (source: Tennis Abstract)",
        fullNote: "Excellent 76.7% win rate, elite return game (41.3% break rate, well above 35.8% average). Her RPW of 46.0% is 5th on tour. The most underrated player in the top 10 statistically — her numbers suggest she should be ranked higher.",
        miamiNote: "A steady competitor who makes opponents beat her cleanly. Her consistency makes her difficult to dispatch in best-of-three formats and she has the experience to go deep.",
        surfaceNote: { hard: "Solid on hard — consistency keeps her competitive.", clay: "Good on clay — works hard for every point.", grass: "Strong on grass — has made deep Wimbledon runs." }
      },
      "Muchova": {
        eloRank: 9, elo: 2041,
        hElo: 2012.0, hEloRank: 7, cElo: 1843.7, cEloRank: 12, gElo: 1767.0, gEloRank: 14, peakElo: 2050.8, peakMonth: "2026-03",
        yEloRank: 6,  yElo2026: 2070.9, record2026: "14-3 — Best form of her career in 2026. #6 yElo with only 3 losses is extraordinary.",
        record: "29-14 (67.4%) last 52 weeks",
        style: "Creative all-court player",
        strengths: "Variety, drop shots, net play, slice backhand",
        serveStats: "Hold 76.6%, Ace 5.0%, DF 2.7% — second lowest DF rate in top 10",
        returnStats: "RPW 42.2%, Break rate 30.3% — below tour average",
        bpStats: "Break point conversion 39.4% — lowest in top 10, Save rate 59.6% — above average",
        overallStats: "DR 1.10, TPW 51.6%, Tiebreak 53.8%",
        h2h: "vs Sabalenka 1-4 · vs Swiatek 2-5 · vs Rybakina 1-2 · vs Gauff 2-2 (source: Tennis Abstract)",
        fullNote: "Low DF rate (2.7%) shows she keeps the ball in play well. Her 30.3% break rate is below tour average which reflects her creative rather than power-based return game. Her variety and net play create problems opponents struggle to solve even when her stats look modest.",
        miamiNote: "A genuinely difficult stylistic matchup for any player. Her drop shots, net presence, and slice create problems on all surfaces. One of the most tactically interesting players in the draw.",
        surfaceNote: { hard: "Effective on hard — variety creates problems for power baseliners.", clay: "Strong on clay — Roland Garros finalist.", grass: "Good on grass — her net play is a natural fit." }
      },
      "Bencic": {
        eloRank: 10, elo: 1988,
        hElo: 1944.1, hEloRank: 10, cElo: 1791.0, cEloRank: 28, gElo: 1790.4, gEloRank: 10, peakElo: 2100.0, peakMonth: "2015-09",
        yEloRank: 9,  yElo2026: 1914.4, record2026: "9-3 — Strong return from maternity leave. #9 in-season form confirms she is back.",
        record: "31-15 (67.4%) last 52 weeks",
        style: "All-court attacker",
        strengths: "One-handed backhand slice, return game, variety",
        serveStats: "Hold 72.1%, Ace 2.9% — lowest ace rate in top 10, DF 4.1%",
        returnStats: "RPW 43.0%, Break rate 33.0% — below tour average",
        bpStats: "Break point conversion 44.7%, Save rate 60.5% — above average",
        overallStats: "DR 1.06, TPW 51.2%, Tiebreak 66.7%",
        fullNote: "Lowest ace rate in top 10 (2.9%) — wins points through placement and variety, not power. Her return (33% break rate) is below tour average but her winners-to-UFE ratio is elite — she generates offense cleanly. One of the hardest players to read stylistically.",
        miamiNote: "Best winners-to-UFE ratio in the data set. Returning to full form after maternity leave and clearly playing well. A dangerous floater who generates offense without unforced errors.",
        surfaceNote: { hard: "Strong on hard courts historically.", clay: "Solid on clay.", grass: "Good on grass — Olympic gold medalist 2020." }
      },
      // ATP ranks 11-25 — Source: Tennis Abstract Elo/yElo/Serve/Return/BP/Overall tables (March 16, 2026)
      "Tien": {
        eloRank: 11, elo: 1972,
        hElo: 1933.5, hEloRank: 9, cElo: 1638.4, cEloRank: 106, gElo: 1728.4, gEloRank: 28, peakElo: 1977.4, peakMonth: "2026-03",
        yEloRank: 11, yElo2026: 1931.3, record2026: "10-5 — Strong season for a 20-year-old. #11 in-season form is impressive.",
        record: "40-24 (62.5%) last 52 weeks",
        style: "Aggressive hard court baseliner",
        strengths: "Power groundstrokes, explosive movement, strong hard court game",
        serveStats: "Hold 80.2%, Ace 6.8%, DF 5.0% — above average DF rate",
        returnStats: "RPW 36.9%, Break rate 22.3% — slightly above tour average of 21.3%",
        bpStats: "Break point conversion 41.3%, Save rate 62.3%",
        overallStats: "DR 1.03, TPW 50.7%, Tiebreak 67.5%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-1 · vs Medvedev 0-0 · vs Bublik 0-0 (source: Tennis Abstract H2H matrix — limited top-15 record)",
        fullNote: "At 20 years old, Tien is one of the most exciting young Americans on tour. His hElo of 1933 ranks #9 — elite on hard. His clay Elo (#106) reveals a massive surface gap — he is essentially a hard court specialist at this stage. DR 1.03 is modest but expected at his age. 67.5% tiebreak rate is a genuine strength.",
        surfaceNote: { hard: "Elo rank #9 on hard courts — elite for his age. His best surface by a wide margin.", clay: "Clay Elo rank #106 — massive weakness. Fade him heavily at Roland Garros.", grass: "Grass Elo rank #28 — developing but not yet proven." }
      },
      "Draper": {
        eloRank: 12, elo: 1956,
        hElo: 1914.3, hEloRank: 11, cElo: 1828.4, cEloRank: 20, gElo: 1765.3, gEloRank: 17, peakElo: 2103.8, peakMonth: "2025-04",
        yEloRank: 34, yElo2026: 1813.3, record2026: "5-2 — Small sample. Injury-affected start to 2026.",
        record: "22-9 (71.0%) last 52 weeks",
        style: "Aggressive left-handed baseliner",
        strengths: "Heavy topspin forehand, serve, physicality",
        serveStats: "Hold 86.8%, Ace 10.5%, DF 3.6%",
        returnStats: "RPW 38.4%, Break rate 24.2% — above tour average",
        bpStats: "Break point conversion 37.1%, Save rate 66.0%",
        overallStats: "DR 1.23, TPW 52.8%, Tiebreak 70.0%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "DR 1.23 is elite — ranks among the top 5 on tour. His 70% tiebreak rate is exceptional. The gap between his peak Elo (2103 in April 2025) and current yElo rank (#34) reflects injury disruption in 2026. When healthy he is a genuine top-5 caliber player. Left-handed serve creates unique problems for opponents.",
        surfaceNote: { hard: "Hard court Elo #11 — elite. Best results on hard.", clay: "Clay Elo #20 — solid, improving.", grass: "Grass Elo #17 — strong, benefits from left-handed serve at Wimbledon." }
      },
      "Fils": {
        eloRank: 13, elo: 1956,
        hElo: 1903.0, hEloRank: 15, cElo: 1883.8, cEloRank: 11, gElo: 1763.8, gEloRank: 18, peakElo: 1985.3, peakMonth: "2025-04",
        yEloRank: 8, yElo2026: 1948.6, record2026: "9-4 — #8 in-season form. Strong 2026 start.",
        record: "23-10 (69.7%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Explosive groundstrokes, athleticism, competitive fire",
        serveStats: "Hold 82.3%, Ace 6.2%, DF 3.3%",
        returnStats: "RPW 37.5%, Break rate 22.3% — slightly above tour average",
        bpStats: "Break point conversion 38.8%, Save rate 59.8% — below average",
        overallStats: "DR 1.08, TPW 51.2%, Tiebreak 52.9%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Young Frenchman with legitimate top-10 upside. Clay Elo #11 is notable — he is not just a hard court player. BP save rate (59.8%) is below average which is his primary vulnerability. 52.9% tiebreak rate is essentially coin-flip — he struggles to close tight sets.",
        surfaceNote: { hard: "Hard Elo #15 — solid.", clay: "Clay Elo #11 — genuine clay threat. Watch at Roland Garros.", grass: "Grass Elo #18 — still developing." }
      },
      "Bublik": {
        eloRank: 14, elo: 1952,
        hElo: 1874.4, hEloRank: 16, cElo: 1900.1, cEloRank: 9, gElo: 1845.1, gEloRank: 9, peakElo: 1988.6, peakMonth: "2026-01",
        yEloRank: 20, yElo2026: 1856.8, record2026: "13-5 — Solid 2026.",
        record: "48-19 (71.6%) last 52 weeks",
        style: "Unorthodox serve-and-volley big server",
        strengths: "Enormous serve, net presence, unpredictability",
        serveStats: "Hold 88.2%, Ace 14.7%, DF 5.7% — very high DF rate",
        returnStats: "RPW 34.7%, Break rate 18.2% — below tour average",
        bpStats: "Break point conversion 39.3%, Save rate 70.9% — elite",
        overallStats: "DR 1.09, TPW 51.6%, Tiebreak 60.0%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-1 · vs Djokovic 0-1 · vs Zverev 1-3 · vs Medvedev 1-7 · vs Musetti 0-0 · vs De Minaur 1-2 · vs FAA 3-4 · vs Shelton 1-2 · vs Fritz 0-0 · vs Ruud 0-0 · vs Mensik 2-1 · vs Cobolli 0-1 · vs Khachanov 1-1 (source: Tennis Abstract H2H matrix)",
        fullNote: "The most unpredictable player in the top 15. 14.7% ace rate is elite but 5.7% DF rate is a volatility risk. BP save rate of 70.9% is his superpower — he rarely gets broken when he holds his nerve. Return game (18.2% break rate) is the weakness — below tour average. His clay Elo (#9) is surprisingly strong for a serve-based player.",
        surfaceNote: { hard: "Hard Elo #16 — solid but not elite.", clay: "Clay Elo #9 — surprisingly strong. His serve works on clay too.", grass: "Grass Elo #9 — thrives on fast surfaces where his serve dominates." }
      },
      "Mensik": {
        eloRank: 15, elo: 1940,
        hElo: 1904.9, hEloRank: 13, cElo: 1800.4, cEloRank: 24, gElo: 1731.3, gEloRank: 25, peakElo: 1969.6, peakMonth: "2026-02",
        yEloRank: 9, yElo2026: 1938.0, record2026: "14-5 — #9 in-season form. Excellent 2026.",
        record: "38-19 (66.7%) last 52 weeks",
        style: "Big serving aggressive baseliner",
        strengths: "Serve, forehand power, mental composure for his age",
        serveStats: "Hold 85.0%, Ace 15.9% — one of the highest on tour, DF 4.7%",
        returnStats: "RPW 36.3%, Break rate 20.1% — just below tour average",
        bpStats: "Break point conversion 40.2%, Save rate 65.1%",
        overallStats: "DR 1.08, TPW 51.3%, Tiebreak 66.7%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 · vs Bublik 1-2 · vs Ruud 0-2 · vs Cobolli 1-1 · vs Khachanov 0-2 (source: Tennis Abstract H2H matrix)",
        fullNote: "At 20, Mensik has the highest ace rate in the top 15 (15.9%). His serve is already a tour-level weapon. Return game (20.1% break rate) is just below average — the area to improve. 66.7% tiebreak rate is strong. His clay Elo (#24) shows he is not a pure hard court specialist.",
        surfaceNote: { hard: "Hard Elo #13 — strong. His serve plays well on hard.", clay: "Clay Elo #24 — solid for a young big server.", grass: "Grass Elo #25 — expected to improve as his serve matures." }
      },
      "Ruud": {
        eloRank: 16, elo: 1934,
        hElo: 1872.2, hEloRank: 18, cElo: 1939.2, cEloRank: 6, gElo: 1690.4, gEloRank: 45, peakElo: 2071.9, peakMonth: "2022-05",
        yEloRank: 35, yElo2026: 1812.6, record2026: "7-6 — Below his best. yElo #35 reflects a difficult start.",
        record: "36-19 (65.5%) last 52 weeks",
        style: "Clay court baseliner",
        strengths: "Heavy topspin, consistency on clay, high ball trajectory",
        serveStats: "Hold 85.4%, Ace 8.8%, DF 2.6% — low DF rate",
        returnStats: "RPW 36.1%, Break rate 20.9% — just below tour average",
        bpStats: "Break point conversion 39.1%, Save rate 68.0%",
        overallStats: "DR 1.08, TPW 51.4%, Tiebreak 64.7%",
        h2h: "vs Alcaraz 1-6 · vs Sinner 0-4 · vs Djokovic 1-5 · vs Zverev 4-2 · vs Musetti 2-2 · vs De Minaur 2-2 · vs FAA 5-4 · vs Shelton 2-2 · vs Medvedev 3-1 · vs Bublik 0-0 · vs Khachanov 1-2 (source: Tennis Abstract H2H matrix)",
        fullNote: "Clay Elo #6 on tour — legitimate Roland Garros threat every year. Grass Elo #45 reveals the surface weakness clearly. His hard court Elo (#18) is solid but not elite. Low DF rate (2.6%) shows controlled serving. His yElo rank (#35) in 2026 suggests below-par form — worth monitoring at Miami where hard courts are not his best surface.",
        surfaceNote: { hard: "Hard Elo #18 — solid but not elite. Miami is not his best event.", clay: "Clay Elo #6 — genuine Roland Garros contender every year.", grass: "Grass Elo #45 — significant weakness. Exits early at Wimbledon typically." }
      },
      "Korda": {
        eloRank: 17, elo: 1915,
        hElo: 1873.0, hEloRank: 17, cElo: 1780.8, cEloRank: 30, gElo: 1789.9, gEloRank: 13, peakElo: 2020.7, peakMonth: "2023-01",
        yEloRank: 10, yElo2026: 1936.6, record2026: "14-6 — #10 in-season form. Strong 2026 start.",
        record: "29-19 (60.4%) last 52 weeks",
        style: "All-court attacker",
        strengths: "Serve, forehand, athleticism",
        serveStats: "Hold 84.9%, Ace 12.1%, DF 3.0%",
        returnStats: "RPW 36.7%, Break rate 20.1% — just below tour average",
        bpStats: "Break point conversion 38.7%, Save rate 63.5%",
        overallStats: "DR 1.12, TPW 51.7%, Tiebreak 52.6% — below average tiebreaks",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "DR 1.12 is solid. His 12.1% ace rate is a genuine weapon. The concern is tiebreaks — 52.6% is essentially coin-flip, meaning he struggles to convert close sets. Grass Elo #13 is a hidden strength — he may be underrated at Wimbledon. His yElo #10 confirms genuine 2026 form.",
        surfaceNote: { hard: "Hard Elo #17 — solid.", clay: "Clay Elo #30 — below average on clay.", grass: "Grass Elo #13 — underrated on grass. Worth watching at Wimbledon." }
      },
      "Fonseca": {
        eloRank: 18, elo: 1912,
        hElo: 1904.5, hEloRank: 14, cElo: 1784.7, cEloRank: 29, gElo: 1697.0, gEloRank: 43, peakElo: 1992.5, peakMonth: "2025-03",
        yEloRank: 55, yElo2026: 1745.6, record2026: "4-4 — Small sample, mixed results.",
        record: "23-16 (59.0%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Explosive groundstrokes, raw talent, hard court game",
        serveStats: "Hold 85.1%, Ace 8.1%, DF 2.6%",
        returnStats: "RPW 35.8%, Break rate 19.4% — below tour average",
        bpStats: "Break point conversion 35.2%, Save rate 61.8%",
        overallStats: "DR 1.08, TPW 51.0%, Tiebreak 44.0% — significant weakness",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 (source: Tennis Abstract — very limited top-15 record)",
        fullNote: "At 19, Fonseca is the youngest player in the top 20. His hElo of 1904 ranks #14 — elite for his age on hard. The glaring weakness is tiebreaks at 44% — well below average. He loses more tiebreaks than he wins, which caps his ceiling in tight matches. BP conversion (35.2%) is the lowest in the top 20. Enormous upside but raw.",
        surfaceNote: { hard: "Hard Elo #14 — exceptional for a 19-year-old.", clay: "Clay Elo #29 — developing.", grass: "Grass Elo #43 — very limited grass experience." }
      },
      "Paul": {
        eloRank: 19, elo: 1905,
        hElo: 1850.5, hEloRank: 21, cElo: 1843.0, cEloRank: 17, gElo: 1750.1, gEloRank: 21, peakElo: 2028.8, peakMonth: "2025-05",
        yEloRank: 12, yElo2026: 1897.1, record2026: "12-6 — #12 in-season form. Solid 2026.",
        record: "29-15 (65.9%) last 52 weeks",
        style: "All-court baseliner",
        strengths: "Consistency, return game, two-handed backhand",
        serveStats: "Hold 83.5%, Ace 7.5%, DF 2.4% — low DF rate",
        returnStats: "RPW 37.9%, Break rate 23.6% — above tour average",
        bpStats: "Break point conversion 42.0%, Save rate 64.6%",
        overallStats: "DR 1.12, TPW 51.8%, Tiebreak 57.1%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "One of the most balanced profiles in the top 20. Low DF rate (2.4%), solid break rate (23.6% — above average), BP conversion 42%. Clay Elo #17 is surprisingly strong — he is not a pure hard court specialist. DR 1.12 is solid. A reliable, consistent player without glaring weaknesses.",
        surfaceNote: { hard: "Hard Elo #21 — solid.", clay: "Clay Elo #17 — stronger on clay than his reputation suggests.", grass: "Grass Elo #21 — capable on all surfaces." }
      },
      "Fokina": {
        eloRank: 20, elo: 1904,
        hElo: 1857.9, hEloRank: 19, cElo: 1821.3, cEloRank: 22, gElo: 1729.8, gEloRank: 27, peakElo: 1934.8, peakMonth: "2025-07",
        yEloRank: 31, yElo2026: 1822.5, record2026: "9-6 — Decent but not elite form.",
        record: "40-25 (61.5%) last 52 weeks",
        style: "Aggressive clay court baseliner",
        strengths: "Heavy topspin, clay court movement, forehand",
        serveStats: "Hold 81.8%, Ace 4.9% — low ace rate, DF 2.6%",
        returnStats: "RPW 38.2%, Break rate 24.9% — above tour average",
        bpStats: "Break point conversion 43.2%, Save rate 68.2%",
        overallStats: "DR 1.07, TPW 51.4%, Tiebreak 48.5% — below average",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs De Minaur 1-4 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Strong return game — 38.2% RPW and 43.2% BP conversion are both solid. But tiebreaks at 48.5% is a liability — he loses more tiebreaks than he wins. Low ace rate (4.9%) means he can't bail himself out with free points. Best on clay where his topspin and movement neutralize big servers.",
        surfaceNote: { hard: "Hard Elo #19 — solid but not elite. Miami suits him reasonably.", clay: "Clay Elo #22 — genuine clay threat.", grass: "Grass Elo #27 — limited grass upside." }
      },
      "Rublev": {
        eloRank: 21, elo: 1896,
        hElo: 1852.7, hEloRank: 20, cElo: 1856.3, cEloRank: 16, gElo: 1797.6, gEloRank: 12, peakElo: 2122.1, peakMonth: "2021-04",
        yEloRank: 21, yElo2026: 1854.0, record2026: "10-5 — Solid but well below his 2021 peak.",
        record: "35-24 (59.3%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Forehand, work rate, consistency",
        serveStats: "Hold 84.3%, Ace 10.1%, DF 3.7%",
        returnStats: "RPW 37.2%, Break rate 21.9% — slightly above tour average",
        bpStats: "Break point conversion 38.7%, Save rate 64.3%",
        overallStats: "DR 1.12, TPW 51.7%, Tiebreak 53.3%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 · vs De Minaur 0-0 · vs FAA 0-0 · vs Shelton 0-0 · vs Fritz 0-0 · vs Ruud 0-0 (source: Tennis Abstract — H2H not in top-15 matrix)",
        fullNote: "Career peak of 2122 in April 2021 — he is now 226 points below that. DR 1.12 is solid but tiebreaks at 53.3% reveal a player who struggles in the clutch — consistent with his reputation. Grass Elo #12 is a hidden strength. His forehand is elite but his mental game in big moments has been a recurring issue.",
        surfaceNote: { hard: "Hard Elo #20 — solid.", clay: "Clay Elo #16 — strong on clay, consistent results at Roland Garros.", grass: "Grass Elo #12 — underrated on grass." }
      },
      "Lehecka": {
        eloRank: 22, elo: 1887,
        hElo: 1834.6, hEloRank: 24, cElo: 1780.3, cEloRank: 31, gElo: 1775.9, gEloRank: 15, peakElo: 1989.9, peakMonth: "2025-10",
        yEloRank: 69, yElo2026: 1717.8, record2026: "6-5 — Below his best in 2026.",
        record: "34-23 (59.6%) last 52 weeks",
        style: "Big serving baseliner",
        strengths: "Serve, forehand, power",
        serveStats: "Hold 83.5%, Ace 10.6%, DF 3.0%",
        returnStats: "RPW 35.3%, Break rate 20.0% — just below tour average",
        bpStats: "Break point conversion 41.3%, Save rate 60.6% — below average",
        overallStats: "DR 1.05, TPW 50.8%, Tiebreak 51.9% — near coin-flip",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Grass Elo #15 is his best surface ranking — big servers thrive at Wimbledon. His BP save rate (60.6%) is below average which is a vulnerability when opponents get opportunities. Tiebreaks at 51.9% is essentially coin-flip. yElo rank #69 in 2026 signals he is below his best form right now.",
        surfaceNote: { hard: "Hard Elo #24 — solid.", clay: "Clay Elo #31 — below average on clay.", grass: "Grass Elo #15 — his best surface. Watch at Wimbledon." }
      },
      "Cerundolo": {
        eloRank: 23, elo: 1884,
        hElo: 1836.8, hEloRank: 23, cElo: 1857.6, cEloRank: 15, gElo: 1664.3, gEloRank: 52, peakElo: 1961.6, peakMonth: "2025-04",
        yEloRank: 30, yElo2026: 1823.5, record2026: "11-5 — Solid season.",
        record: "36-24 (60.0%) last 52 weeks",
        style: "Clay court baseliner",
        strengths: "Topspin, clay court footwork, competitive mentality",
        serveStats: "Hold 76.9%, Ace 4.9% — very low, DF 3.6%",
        returnStats: "RPW 40.3%, Break rate 28.8% — well above tour average",
        bpStats: "Break point conversion 43.0%, Save rate 62.7%",
        overallStats: "DR 1.08, TPW 51.5%, Tiebreak 68.2%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Musetti 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Return game is elite — 40.3% RPW and 28.8% break rate are both well above average. 68.2% tiebreak rate is strong. His grass Elo (#52) reveals a player who is essentially a clay and hard court specialist. Low ace rate (4.9%) means his serve is a liability on fast surfaces. A genuine clay court threat.",
        surfaceNote: { hard: "Hard Elo #23 — solid.", clay: "Clay Elo #15 — genuine threat at Roland Garros.", grass: "Grass Elo #52 — significant weakness on grass." }
      },
      "Norrie": {
        eloRank: 24, elo: 1865,
        hElo: 1812.5, hEloRank: 29, cElo: 1833.1, cEloRank: 19, gElo: 1753.1, gEloRank: 20, peakElo: 2028.6, peakMonth: "2022-08",
        yEloRank: 24, yElo2026: 1835.4, record2026: "9-6 — Steady form.",
        record: "36-25 (59.0%) last 52 weeks",
        style: "Left-handed defensive baseliner",
        strengths: "Consistency, retrieval, left-handed slice",
        serveStats: "Hold 81.8%, Ace 5.9% — low, DF 2.8%",
        returnStats: "RPW 36.1%, Break rate 19.6% — below tour average",
        bpStats: "Break point conversion 38.2%, Save rate 67.0%",
        overallStats: "DR 1.02, TPW 50.4%, Tiebreak 58.1%",
        h2h: "vs Alcaraz 0-0 · vs Sinner 0-0 · vs Djokovic 0-0 · vs Zverev 0-0 · vs Medvedev 0-0 · vs Ruud 0-2 · vs Khachanov 2-1 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "DR 1.02 is the lowest in the top 25 — he barely wins more points than he loses, which explains why he beats lower-ranked players comfortably but struggles against the elite. Clay Elo #19 and grass Elo #20 show he is genuinely multi-surface. Low ace rate (5.9%) and below-average break rate (19.6%) are his main limitations.",
        surfaceNote: { hard: "Hard Elo #29 — below average in top 25.", clay: "Clay Elo #19 — strong on clay.", grass: "Grass Elo #20 — benefits from left-handed serve at Wimbledon." }
      },
      "Khachanov": {
        eloRank: 25, elo: 1863,
        hElo: 1804.3, hEloRank: 31, cElo: 1827.5, cEloRank: 21, gElo: 1759.7, gEloRank: 19, peakElo: 2029.5, peakMonth: "2018-10",
        yEloRank: 78, yElo2026: 1700.8, record2026: "6-6 — Below his best. yElo #78 is a significant concern.",
        record: "34-24 (58.6%) last 52 weeks",
        style: "Power baseliner",
        strengths: "Forehand, physicality, big points",
        serveStats: "Hold 84.0%, Ace 8.6%, DF 2.6%",
        returnStats: "RPW 36.6%, Break rate 21.5% — slightly above tour average",
        bpStats: "Break point conversion 39.7%, Save rate 64.0%",
        overallStats: "DR 1.10, TPW 51.4%, Tiebreak 42.4% — worst in top 25",
        h2h: "vs Alcaraz 0-6 · vs Sinner 1-4 · vs Djokovic 1-9 · vs Zverev 3-6 · vs Musetti 0-1 · vs De Minaur 2-2 · vs FAA 2-2 · vs Shelton 0-2 · vs Fritz 0-2 · vs Medvedev 2-7 · vs Ruud 2-1 · vs Mensik 2-0 · vs Cobolli 1-0 (source: Tennis Abstract H2H matrix)",
        fullNote: "Tiebreak rate of 42.4% is the worst in the top 25 — he loses significantly more tiebreaks than he wins. This is his career-defining weakness. yElo #78 in 2026 suggests real form concerns. DR 1.10 is solid when he is on but his peak was back in 2018. Grass Elo #19 is a hidden strength for Wimbledon.",
        surfaceNote: { hard: "Hard Elo #31 — below average in top 25.", clay: "Clay Elo #21 — solid on clay.", grass: "Grass Elo #19 — underrated on grass." }
      },
    },
    wta: {
      // Source: Tennis Abstract Elo/yElo/Serve/Return/BP/Overall tables (March 16, 2026)
      // Tour averages: SPW 59.1%, RPW 44.0%, Brk% 35.8%, tour avg hold 70.9%
      "Sabalenka": {
        eloRank: 1, elo: 2247,
        hElo: 2203.9, hEloRank: 1, cElo: 2142.8, cEloRank: 1, gElo: 2000.2, gEloRank: 1, peakElo: 2247.1, peakMonth: "2026-03",
        yEloRank: 1, yElo2026: 2199.2, record2026: "17-1 — #1 in-season form. Currently at career peak Elo. Dominant 2026.",
        record: "63-9 (87.5%) last 52 weeks",
        style: "Aggressive power baseliner",
        strengths: "Serve, forehand, physicality, mental toughness under pressure",
        serveStats: "Hold 79.9%, Ace 6.6%, DF 3.3%",
        returnStats: "RPW 45.3%, Break rate 38.0% — well above tour average of 35.8%",
        bpStats: "Break point conversion 44.5%, Save rate 66.0%",
        overallStats: "DR 1.49 equivalent, TPW ~56%, Tiebreak 92.3% (24-2) — historically extraordinary",
        h2h: "vs Rybakina 9-7 · vs Swiatek 5-8 · vs Gauff 6-6 · vs Pegula 9-3 · vs Anisimova 2-5 · vs Paolini 2-6 · vs Svitolina 6-1 · vs Mboko 2-0 · vs Andreeva 4-2 · vs Muchova 4-1 · vs Bencic 2-1 · vs Noskova 0-2 · vs Khachanov 0-0 · vs Osaka 1-1 (source: Tennis Abstract H2H matrix)",
        fullNote: "#1 Elo on hard, clay AND grass simultaneously — unprecedented in the modern era. 92.3% tiebreak rate (24-2) is historically extraordinary. Currently at her career peak Elo of 2247 in March 2026. Her 38% break rate and 45.3% RPW are both elite. The clear favorite at every hard court event.",
        surfaceNote: { hard: "#1 hElo on tour (2203.9). Hard court is her best surface.", clay: "#1 cElo on tour (2142.8) — dominant on clay too.", grass: "#1 gElo on tour (2000.2) — elite on all three surfaces." }
      },
      "Rybakina": {
        eloRank: 2, elo: 2163,
        hElo: 2124.3, hEloRank: 2, cElo: 2006.4, cEloRank: 4, gElo: 1915.4, gEloRank: 3, peakElo: 2176.7, peakMonth: "2026-02",
        yEloRank: 3, yElo2026: 2124.2, record2026: "17-4 — #3 in-season form. Strong 2026.",
        record: "61-17 (78.2%) last 52 weeks",
        style: "Serve-and-baseline power player",
        strengths: "Serve, flat groundstrokes, net presence",
        serveStats: "Hold 83.6%, Ace 10.3%, DF 3.7%",
        returnStats: "RPW 42.7%, Break rate 33.0% — below tour average",
        bpStats: "Break point conversion 45.3%, Save rate 66.7%",
        overallStats: "DR high, TPW ~53%, Tiebreak strong",
        h2h: "vs Sabalenka 7-9 · vs Swiatek 6-6 · vs Gauff 1-0 · vs Pegula 0-3 · vs Anisimova 1-3 · vs Paolini 3-3 · vs Svitolina 3-4 · vs Mboko 2-2 · vs Andreeva 2-1 · vs Muchova 2-1 · vs Bencic 2-4 · vs Noskova 3-0 · vs Osaka 1-2 (source: Tennis Abstract H2H matrix)",
        fullNote: "10.3% ace rate is the best on the WTA tour — her serve is a genuine weapon at a level rare in women's tennis. Break rate (33%) is below tour average (35.8%) which is the key weakness — she wins through her serve dominance rather than her return. Grass Elo #3 confirms she is elite on fast surfaces. Currently near her career peak.",
        surfaceNote: { hard: "#2 hElo (2124.3) — elite on hard.", clay: "#4 cElo (2006.4) — strong on clay.", grass: "#3 gElo (1915.4) — best surface relative to others. Wimbledon champion 2022." }
      },
      "Swiatek": {
        eloRank: 3, elo: 2110,
        hElo: 2055.5, hEloRank: 4, cElo: 2054.3, cEloRank: 2, gElo: 1950.7, gEloRank: 2, peakElo: 2291.0, peakMonth: "2024-07",
        yEloRank: 7, yElo2026: 1957.7, record2026: "12-5 — #7 in-season form. Weakest season start in years. 181 points below her 2024 peak.",
        record: "56-17 (76.7%) last 52 weeks",
        style: "Heavy topspin aggressive baseliner",
        strengths: "Return game, forehand topspin, clay court dominance",
        serveStats: "Hold 75.1%, Ace 5.6%, DF 5.1% — high DF rate, above average",
        returnStats: "RPW 47.3%, Break rate 43.8% — #1 on tour",
        bpStats: "Break point conversion 51.2%, Save rate 58.5% — below average",
        overallStats: "DR high, TPW ~53%, Tiebreak moderate",
        h2h: "vs Sabalenka 8-5 · vs Rybakina 6-6 · vs Gauff 11-5 · vs Pegula 5-6 · vs Anisimova 1-2 · vs Paolini 6-1 · vs Svitolina 4-1 · vs Mboko 0-0 · vs Andreeva 1-2 · vs Muchova 5-1 · vs Bencic 5-2 · vs Noskova 6-1 · vs Kostyuk 0-0 · vs Osaka 2-1 (source: Tennis Abstract H2H matrix)",
        fullNote: "#1 break rate on tour (43.8%) and #1 RPW — she dominates through return not serve. Hold rate of 75.1% is notably low — her serve is a relative weakness. BP save rate 58.5% is below average. She is 181 points below her July 2024 peak of 2291 — clearly in a form slump by her own historical standards. yElo #7 in 2026 is her worst season start in years.",
        surfaceNote: { hard: "#4 hElo (2055.5) — solid but not dominant on hard.", clay: "#2 cElo (2054.3) — clay is her best surface. Has dominated Roland Garros.", grass: "#2 gElo (1950.7) — stronger on grass than her reputation suggests." }
      },
      "Pegula": {
        eloRank: 4, elo: 2094,
        hElo: 2056.0, hEloRank: 3, cElo: 1909.1, cEloRank: 8, gElo: 1876.9, gEloRank: 5, peakElo: 2101.6, peakMonth: "2026-03",
        yEloRank: 2, yElo2026: 2131.5, record2026: "16-3 — #2 in-season form. Best season of her career. Currently at career peak Elo.",
        record: "54-21 (72.0%) last 52 weeks",
        style: "Hard court baseliner",
        strengths: "Consistency, return game, hard court game",
        serveStats: "Hold 75.0%, Ace 4.6% — low, DF 3.0%",
        returnStats: "RPW 45.1%, Break rate 38.1% — above tour average",
        bpStats: "Break point conversion 45.1%, Save rate 59.8% — below average",
        overallStats: "DR solid, TPW ~52%, Tiebreak moderate",
        h2h: "vs Sabalenka 3-9 · vs Rybakina 3-0 · vs Swiatek 6-5 · vs Gauff 3-3 · vs Anisimova 5-0 · vs Paolini 6-1 · vs Svitolina 3-6 · vs Mboko 0-0 · vs Andreeva 3-3 · vs Muchova 2-4 · vs Bencic 1-4 · vs Noskova 1-2 · vs Osaka 1-1 (source: Tennis Abstract H2H matrix)",
        fullNote: "#3 hElo on tour (2056.0) — essentially tied with Swiatek on hard and slightly ahead. Clay is dramatically weaker (#8, 1909) — a 147-point gap. She is a hard court specialist. Currently at her career peak Elo (2101.6 this month). yElo #2 confirms this is genuinely the best form of her career. Massively underrated by the market relative to her actual current level.",
        surfaceNote: { hard: "#3 hElo (2056.0) — elite on hard. Miami suits her perfectly.", clay: "#8 cElo (1909.1) — significant weakness on clay. Fade at Roland Garros.", grass: "#5 gElo (1876.9) — capable on grass." }
      },
      "Gauff": {
        eloRank: 5, elo: 2074,
        hElo: 2017.0, hEloRank: 6, cElo: 2044.5, cEloRank: 3, gElo: 1842.7, gEloRank: 6, peakElo: 2155.7, peakMonth: "2024-01",
        yEloRank: 14, yElo2026: 1909.8, record2026: "11-5 — #14 in-season form. Underperforming vs ranking.",
        record: "48-17 (73.8%) last 52 weeks",
        style: "Athletic all-court player",
        strengths: "Return game, athleticism, clay court movement",
        serveStats: "Hold 65.6%, Ace 3.4% — very low, DF 10.4% — highest on tour",
        returnStats: "RPW 49.3%, Break rate 48.1% — elite return game",
        bpStats: "Break point conversion 53.1%, Save rate 51.3% — well below average",
        overallStats: "DR moderate, TPW ~51%, Tiebreak moderate",
        h2h: "vs Sabalenka 6-6 · vs Rybakina 0-1 · vs Swiatek 5-11 · vs Pegula 3-3 · vs Anisimova 4-3 · vs Paolini 4-3 · vs Svitolina 2-3 · vs Mboko 1-1 · vs Andreeva 0-4 · vs Muchova 2-2 · vs Bencic 2-4 · vs Noskova 2-0 · vs Osaka 3-3 (source: Tennis Abstract H2H matrix)",
        fullNote: "10.4% DF rate is the highest on the entire WTA tour — this is her defining weakness. BP save rate (51.3%) is well below average. However her return game is elite — 49.3% RPW and 48.1% break rate are both top of tour. Clay Elo #3 (2044.5) is actually higher than her hard Elo (#6, 2017) — clay is her best surface by this metric. yElo #14 in 2026 signals underperformance relative to ranking.",
        surfaceNote: { hard: "#6 hElo (2017.0) — solid.", clay: "#3 cElo (2044.5) — clay is actually her best surface. Roland Garros threat.", grass: "#6 gElo (1842.7) — grass is her weakest surface." }
      },
      "Mboko": {
        eloRank: 6, elo: 2072,
        hElo: 2037.4, hEloRank: 5, cElo: 1862.4, cEloRank: 10, gElo: 1749.6, gEloRank: 21, peakElo: 2082.1, peakMonth: "2026-03",
        yEloRank: 5, yElo2026: 2087.4, record2026: "16-5 — #5 in-season form. Currently at career peak Elo.",
        record: "38-15 (71.7%) last 52 weeks",
        style: "Aggressive hard court baseliner",
        strengths: "Power, athleticism, hard court game",
        serveStats: "Hold 72.6%, Ace 6.3%, DF 7.1% — high DF rate",
        returnStats: "RPW 44.1%, Break rate 38.2% — above tour average",
        bpStats: "Break point conversion 51.8%, Save rate 55.8% — below average",
        overallStats: "DR 1.07, TPW 51.5%, Tiebreak 37.5% — significant weakness",
        h2h: "vs Sabalenka 0-2 · vs Rybakina 2-2 · vs Swiatek 0-0 · vs Gauff 1-1 · vs Pegula 0-0 · vs Anisimova 1-0 · vs Paolini 0-0 · vs Svitolina 0-0 · vs Andreeva 1-0 · vs Bencic 0-0 · vs Noskova 0-0 (source: Tennis Abstract H2H matrix)",
        fullNote: "#5 hElo (2037.4) — elite on hard. Clay Elo #10 (1862.4) and grass Elo #21 (1749.6) reveal she is a hard court specialist. 7.1% DF rate is high. Tiebreak rate (37.5%) is a serious concern — she loses significantly more tiebreaks than she wins. Currently at career peak Elo. Miami's hard courts are her ideal surface.",
        surfaceNote: { hard: "#5 hElo (2037.4) — Miami is her best tournament type.", clay: "#10 cElo (1862.4) — weaker on clay.", grass: "#21 gElo (1749.6) — grass is her weakest surface." }
      },
      "Anisimova": {
        eloRank: 7, elo: 2050,
        hElo: 2001.5, hEloRank: 8, cElo: 1862.0, cEloRank: 11, gElo: 1885.6, gEloRank: 4, peakElo: 2086.9, peakMonth: "2025-11",
        yEloRank: 16, yElo2026: 1903.8, record2026: "9-5 — Solid but not elite form in 2026.",
        record: "45-18 (71.4%) last 52 weeks",
        style: "Aggressive flat hitter",
        strengths: "Forehand power, flat groundstrokes, serve",
        serveStats: "Hold 73.1%, Ace 5.3%, DF 5.9% — above average DF rate",
        returnStats: "RPW 45.2%, Break rate 38.4% — above tour average",
        bpStats: "Break point conversion 47.3%, Save rate 59.1%",
        overallStats: "DR 1.13, TPW 52.5%, Tiebreak 58.8%",
        h2h: "vs Sabalenka 5-2 · vs Rybakina 3-1 · vs Swiatek 2-1 · vs Gauff 3-4 · vs Pegula 0-5 · vs Paolini 1-4 · vs Svitolina 1-4 · vs Mboko 0-1 · vs Andreeva 2-1 · vs Muchova 2-2 · vs Bencic 2-2 · vs Noskova 2-1 · vs Osaka 0-3 (source: Tennis Abstract H2H matrix)",
        fullNote: "Grass Elo #4 (1885.6) is her best surface ranking — her flat hitting is a natural fit for Wimbledon. Her DF rate (5.9%) is the vulnerability — she can lose serve unexpectedly. Return game (38.4% break rate) is above tour average. When on she can beat anyone. yElo #16 suggests she hasn't hit top gear yet in 2026.",
        surfaceNote: { hard: "#8 hElo (2001.5) — solid on hard.", clay: "#11 cElo (1862.0) — clay is weakest surface.", grass: "#4 gElo (1885.6) — best surface. Underrated at Wimbledon." }
      },
      "Svitolina": {
        eloRank: 8, elo: 2050,
        hElo: 1993.6, hEloRank: 9, cElo: 1955.7, cEloRank: 5, gElo: 1826.0, gEloRank: 7, peakElo: 2120.6, peakMonth: "2018-05",
        yEloRank: 4, yElo2026: 2113.1, record2026: "19-4 — Most wins on WTA tour in 2026. #4 in-season form. Massively underrated.",
        record: "46-14 (76.7%) last 52 weeks",
        style: "Counter-punching defensive baseliner",
        strengths: "Consistency, retrieval, mental toughness, low error rate",
        serveStats: "Hold 73.9%, Ace 4.9%, DF 4.3%",
        returnStats: "RPW 46.0%, Break rate 41.3% — well above tour average",
        bpStats: "Break point conversion 52.1% — elite, Save rate 60.5%",
        overallStats: "DR 1.14, TPW 53.0%, Tiebreak 66.7%",
        h2h: "vs Sabalenka 1-6 · vs Rybakina 4-3 · vs Swiatek 1-4 · vs Gauff 3-2 · vs Pegula 6-3 · vs Anisimova 4-1 · vs Paolini 1-2 · vs Mboko 0-0 · vs Andreeva 1-1 · vs Muchova 3-2 · vs Bencic 4-2 · vs Noskova 0-3 · vs Osaka 5-3 (source: Tennis Abstract H2H matrix)",
        fullNote: "Most wins on the WTA tour in 2026 (19-4) yet barely mentioned in Miami discussions. Clay Elo #5 (1955.7) — genuine multi-surface threat. Break rate 41.3% and RPW 46% are both well above tour averages. BP conversion 52.1% is elite. yElo #4 at 2113.1 confirms this is her best form in years. The most underrated player in the top 10.",
        surfaceNote: { hard: "#9 hElo (1993.6) — solid on hard.", clay: "#5 cElo (1955.7) — clay is her second best surface.", grass: "#7 gElo (1826.0) — strong on grass, deep Wimbledon runs historically." }
      },
      "Muchova": {
        eloRank: 9, elo: 2041,
        hElo: 2012.0, hEloRank: 7, cElo: 1843.7, cEloRank: 12, gElo: 1767.0, gEloRank: 14, peakElo: 2050.8, peakMonth: "2026-03",
        yEloRank: 6, yElo2026: 2070.9, record2026: "14-3 — #6 in-season form. Best form of her career in 2026.",
        record: "29-14 (67.4%) last 52 weeks",
        style: "Creative all-court player",
        strengths: "Variety, drop shots, net play, slice backhand",
        serveStats: "Hold 76.6%, Ace 5.0%, DF 2.7% — second lowest DF rate in top 10",
        returnStats: "RPW 42.2%, Break rate 30.3% — below tour average",
        bpStats: "Break point conversion 39.4% — lowest in top 10, Save rate 59.6%",
        overallStats: "DR 1.10, TPW 51.6%, Tiebreak 53.8%",
        h2h: "vs Sabalenka 1-4 · vs Rybakina 1-2 · vs Swiatek 1-5 · vs Gauff 2-2 · vs Pegula 4-2 · vs Anisimova 2-2 · vs Paolini 0-5 · vs Svitolina 2-3 · vs Mboko 0-0 · vs Andreeva 4-2 · vs Bencic 3-2 · vs Noskova 0-1 · vs Osaka 1-3 (source: Tennis Abstract H2H matrix)",
        fullNote: "#7 hElo (2012.0) — surprisingly strong on hard courts. Currently at her career peak Elo (March 2026). BP conversion (39.4%) is the lowest in the top 10 — she creates chances but doesn't always convert. Her variety and net play create tactical problems that statistics don't fully capture. yElo #6 in 2026 confirms exceptional current form.",
        surfaceNote: { hard: "#7 hElo (2012.0) — strong on hard, better than her reputation.", clay: "#12 cElo (1843.7) — clay is her weakest surface.", grass: "#14 gElo (1767.0) — her net play suits grass." }
      },
      "Bencic": {
        eloRank: 10, elo: 1988,
        hElo: 1944.1, hEloRank: 10, cElo: 1791.0, cEloRank: 28, gElo: 1790.4, gEloRank: 10, peakElo: 2100.0, peakMonth: "2015-09",
        yEloRank: 9, yElo2026: 1914.4, record2026: "9-3 — Strong return from maternity leave. #9 in-season form confirms she is back.",
        record: "31-15 (67.4%) last 52 weeks",
        style: "All-court attacker",
        strengths: "One-handed backhand slice, return game, variety",
        serveStats: "Hold 72.1%, Ace 2.9% — lowest in top 10, DF 4.1%",
        returnStats: "RPW 43.0%, Break rate 33.0% — below tour average",
        bpStats: "Break point conversion 44.7%, Save rate 60.5%",
        overallStats: "DR 1.06, TPW 51.2%, Tiebreak 66.7%",
        h2h: "vs Sabalenka 1-2 · vs Rybakina 4-2 · vs Swiatek 2-5 · vs Gauff 4-2 · vs Pegula 4-1 · vs Anisimova 2-2 · vs Paolini 4-2 · vs Svitolina 2-4 · vs Mboko 0-0 · vs Andreeva 4-5 · vs Muchova 2-3 · vs Noskova 0-1 · vs Osaka 2-4 (source: Tennis Abstract H2H matrix)",
        fullNote: "Clay Elo #28 (1791) vs hard Elo #10 (1944) — a 153-point gap. The biggest surface split in the top 10. Hard is clearly her surface. Lowest ace rate in top 10 (2.9%) — wins through placement and variety. Tiebreak rate 66.7% is strong. Returning from maternity leave in excellent form.",
        surfaceNote: { hard: "#10 hElo (1944.1) — hard is her best surface.", clay: "#28 cElo (1791.0) — dramatic clay weakness.", grass: "#10 gElo (1790.4) — grass equals clay, both weaker than hard." }
      },
      // WTA ranks 11-25
      "Andreeva": {
        eloRank: 11, elo: 1975,
        hElo: 1940.6, hEloRank: 11, cElo: 1914.8, cEloRank: 7, gElo: 1765.9, gEloRank: 15, peakElo: 2159.2, peakMonth: "2025-03",
        yEloRank: 10, yElo2026: 1914.1, record2026: "12-5 — #10 in-season form. Solid 2026.",
        record: "33-18 (64.7%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Return game, clay court movement, topspin forehand",
        serveStats: "Hold 73.4%, Ace 3.4% — very low, DF 6.1% — high",
        returnStats: "RPW 46.6%, Break rate 42.4% — well above tour average",
        bpStats: "Break point conversion 49.9%, Save rate 62.5%",
        overallStats: "DR solid, TPW ~53%, Tiebreak moderate",
        h2h: "vs Sabalenka 2-4 · vs Rybakina 1-2 · vs Swiatek 2-1 · vs Gauff 4-0 · vs Pegula 3-3 · vs Anisimova 1-2 · vs Paolini 2-3 · vs Svitolina 1-1 · vs Mboko 0-1 · vs Muchova 2-4 · vs Bencic 5-4 · vs Noskova 1-0 (source: Tennis Abstract H2H matrix)",
        fullNote: "Clay Elo #7 (1914.8) — clay is actually her second strongest surface. RPW 46.6% and break rate 42.4% are both well above tour average. At 18 she is already the youngest player in the top 15. Her 6.1% DF rate is the vulnerability. She leads Gauff 4-0 in H2H — a remarkable record against a higher-ranked player.",
        surfaceNote: { hard: "#11 hElo (1940.6) — solid on hard.", clay: "#7 cElo (1914.8) — strong on clay. Roland Garros threat.", grass: "#15 gElo (1765.9) — grass is weakest." }
      },
      "Paolini": {
        eloRank: 12, elo: 1965,
        hElo: 1906.1, hEloRank: 15, cElo: 1919.8, cEloRank: 6, gElo: 1792.1, gEloRank: 9, peakElo: 2058.1, peakMonth: "2025-10",
        yEloRank: 52, yElo2026: 1761.3, record2026: "7-6 — yElo #52 signals clear below-par form in 2026.",
        record: "45-22 (67.2%) last 52 weeks",
        style: "Energetic counter-punching baseliner",
        strengths: "Speed, retrieval, clay court consistency",
        serveStats: "Hold 68.4%, Ace 1.8% — lowest on tour, DF 2.1% — lowest on tour",
        returnStats: "RPW 45.3%, Break rate 39.9% — above tour average",
        bpStats: "Break point conversion 47.6%, Save rate 56.4% — below average",
        overallStats: "DR moderate, TPW ~51%, Tiebreak moderate",
        h2h: "vs Sabalenka 6-2 · vs Rybakina 3-3 · vs Swiatek 1-6 · vs Gauff 3-4 · vs Pegula 1-6 · vs Anisimova 4-1 · vs Svitolina 2-1 · vs Mboko 0-0 · vs Andreeva 3-2 · vs Muchova 5-0 · vs Bencic 2-4 · vs Noskova 0-0 · vs Osaka 1-0 (source: Tennis Abstract H2H matrix)",
        fullNote: "Lowest ace rate (1.8%) AND lowest DF rate (2.1%) on tour — the most controlled server in women's tennis. Clay Elo #6 (1919.8) and grass Elo #9 (1792.1) show she is genuinely multi-surface. H2H record vs Sabalenka is 6-2 — one of the most striking anomalies on tour. yElo #52 in 2026 is a significant concern — she is well below her best form.",
        surfaceNote: { hard: "#15 hElo (1906.1) — below average in top 12 on hard.", clay: "#6 cElo (1919.8) — clay is her best surface.", grass: "#9 gElo (1792.1) — solid on grass." }
      },
      "Keys": {
        eloRank: 13, elo: 1963,
        hElo: 1912.6, hEloRank: 12, cElo: 1884.3, cEloRank: 9, gElo: 1779.5, gEloRank: 11, peakElo: 2090.1, peakMonth: "2016-08",
        yEloRank: 32, yElo2026: 1832.9, record2026: "7-4 — Decent but not elite form.",
        record: "26-17 (60.5%) last 52 weeks",
        style: "Power baseliner",
        strengths: "Serve, forehand power, aggressive baseline game",
        serveStats: "Hold 71.3%, Ace 5.3%, DF 5.5% — above average DF rate",
        returnStats: "RPW 43.6%, Break rate 34.0% — just below tour average",
        bpStats: "Break point conversion 43.1%, Save rate 56.6% — below average",
        overallStats: "DR moderate, TPW ~51%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 · vs Gauff 0-0 · vs Pegula 0-3 · vs Anisimova 0-0 · vs Paolini 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Clay Elo #9 (1884.3) is surprisingly strong for a power player — she is more multi-surface than her reputation suggests. BP save rate (56.6%) is below average. yElo #32 in 2026 suggests she is below her best current form. Hard Elo #12 is solid. Peak was back in 2016 — she is a different, more experienced player now.",
        surfaceNote: { hard: "#12 hElo (1912.6) — solid on hard.", clay: "#9 cElo (1884.3) — stronger on clay than expected.", grass: "#11 gElo (1779.5) — capable on all surfaces." }
      },
      "Osaka": {
        eloRank: 14, elo: 1950,
        hElo: 1910.9, hEloRank: 13, cElo: 1812.3, cEloRank: 16, gElo: 1730.0, gEloRank: 28, peakElo: 2193.3, peakMonth: "2021-03",
        yEloRank: 37, yElo2026: 1807.4, record2026: "5-2 — Small sample. yElo #37 indicates below-par form.",
        record: "29-14 (67.4%) last 52 weeks",
        style: "Aggressive power baseliner",
        strengths: "Serve, forehand, hard court game",
        serveStats: "Hold 76.1%, Ace 9.2%, DF 3.7%",
        returnStats: "RPW 43.5%, Break rate 34.2% — just below tour average",
        bpStats: "Break point conversion 48.5%, Save rate 55.6% — below average",
        overallStats: "DR moderate, TPW ~52%, Tiebreak moderate",
        h2h: "vs Sabalenka 1-1 · vs Rybakina 2-1 · vs Swiatek 1-2 · vs Gauff 3-3 · vs Pegula 1-1 · vs Anisimova 3-0 · vs Paolini 0-1 · vs Svitolina 3-5 · vs Muchova 3-1 · vs Bencic 4-2 · vs Noskova 1-0 (source: Tennis Abstract H2H matrix)",
        fullNote: "9.2% ace rate is one of the best on tour — her serve is a genuine weapon. Clay Elo #16 (1812.3) and grass Elo #28 (1730) are both weaker — she is a hard court specialist. BP save rate (55.6%) is below average. She is 243 points below her 2021 peak of 2193 — she has not returned to that level. yElo #37 confirms current below-par form.",
        surfaceNote: { hard: "#13 hElo (1910.9) — hard is her best surface. 4 Slam titles on hard.", clay: "#16 cElo (1812.3) — clay is weaker.", grass: "#28 gElo (1730.0) — grass is her weakest surface." }
      },
      "Noskova": {
        eloRank: 15, elo: 1946,
        hElo: 1906.0, hEloRank: 16, cElo: 1760.7, cEloRank: 37, gElo: 1775.2, gEloRank: 13, peakElo: 1959.9, peakMonth: "2025-10",
        yEloRank: 18, yElo2026: 1896.1, record2026: "9-5 — Solid 2026 form.",
        record: "38-24 (61.3%) last 52 weeks",
        style: "Big serving aggressive baseliner",
        strengths: "Serve, forehand power, hard court game",
        serveStats: "Hold 75.0%, Ace 8.5%, DF 6.7% — very high DF rate",
        returnStats: "RPW 41.2%, Break rate 29.8% — below tour average",
        bpStats: "Break point conversion 43.2%, Save rate 59.0%",
        overallStats: "DR moderate, TPW ~51%, Tiebreak moderate",
        h2h: "vs Sabalenka 2-0 · vs Rybakina 0-3 · vs Swiatek 1-6 · vs Gauff 0-2 · vs Pegula 2-1 · vs Anisimova 1-2 · vs Paolini 0-0 · vs Svitolina 3-0 · vs Mboko 0-0 · vs Andreeva 0-1 · vs Muchova 1-0 · vs Bencic 1-0 · vs Osaka 0-1 (source: Tennis Abstract H2H matrix)",
        fullNote: "Leads Sabalenka 2-0 in H2H — a remarkable record. Grass Elo #13 (1775.2) is stronger than her clay Elo (#37, 1760.7) — she is actually better on grass than clay. Very high DF rate (6.7%) is the primary volatility risk. Break rate (29.8%) is below tour average. Her serve is the weapon.",
        surfaceNote: { hard: "#16 hElo (1906.0) — solid on hard.", clay: "#37 cElo (1760.7) — clay is weakest surface.", grass: "#13 gElo (1775.2) — better on grass than clay. Watch at Wimbledon." }
      },
      "Kostyuk": {
        eloRank: 16, elo: 1941,
        hElo: 1909.8, hEloRank: 14, cElo: 1838.7, cEloRank: 14, gElo: 1679.3, gEloRank: 48, peakElo: 1986.1, peakMonth: "2024-04",
        yEloRank: 29, yElo2026: 1839.6, record2026: "5-3 — Small sample.",
        record: "25-16 (61.0%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Forehand, aggression, hard court game",
        serveStats: "Hold 70.4%, Ace 4.0%, DF 6.8% — high DF rate",
        returnStats: "RPW 44.4%, Break rate 37.8% — above tour average",
        bpStats: "Break point conversion 43.5%, Save rate 62.1%",
        overallStats: "DR moderate, TPW ~52%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 · vs Gauff 0-0 · vs Pegula 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Grass Elo #48 (1679.3) reveals a large surface gap — she is essentially a hard and clay court player. Hard Elo #14 (1909.8) and clay Elo #14 (1838.7) show genuine multi-surface capability on the two non-grass surfaces. Her 6.8% DF rate is the main weakness. yElo #29 suggests she is not in peak form in 2026.",
        surfaceNote: { hard: "#14 hElo (1909.8) — solid on hard.", clay: "#14 cElo (1838.7) — equally solid on clay.", grass: "#48 gElo (1679.3) — significant grass weakness." }
      },
      "Vondrousova": {
        eloRank: 17, elo: 1932,
        hElo: 1850.8, hEloRank: 20, cElo: 1798.1, cEloRank: 26, gElo: 1816.1, gEloRank: 8, peakElo: 2062.5, peakMonth: "2023-08",
        yEloRank: 0, yElo2026: 0, record2026: "Limited data — injury-affected",
        record: "15-7 (68.2%) last 52 weeks",
        style: "Left-handed creative baseliner",
        strengths: "Left-handed spin, drop shots, variety",
        serveStats: "Hold 72.4%, Ace 5.7%, DF 7.5% — very high DF rate",
        returnStats: "RPW 44.4%, Break rate 37.1% — above tour average",
        bpStats: "Break point conversion 42.4%, Save rate 61.5%",
        overallStats: "DR moderate, TPW ~51%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 (source: Tennis Abstract — limited record)",
        fullNote: "Grass Elo #8 (1816.1) is her best surface ranking — Wimbledon champion 2023. Her left-handed serve and variety are a natural fit for grass. 7.5% DF rate is the highest in the top 20 — a significant volatility risk. Hard Elo #20 (1850.8) is below the top 15 level. She appears to be returning from injury in 2026 with a very limited match record.",
        surfaceNote: { hard: "#20 hElo (1850.8) — below average in top 20 on hard.", clay: "#26 cElo (1798.1) — modest clay game.", grass: "#8 gElo (1816.1) — best surface. Wimbledon champion 2023." }
      },
      "Kalinskaya": {
        eloRank: 18, elo: 1926,
        hElo: 1881.3, hEloRank: 18, cElo: 1770.2, cEloRank: 31, gElo: 1743.9, gEloRank: 23, peakElo: 1948.6, peakMonth: "2024-04",
        yEloRank: 17, yElo2026: 1897.7, record2026: "9-6 — Solid 2026 form.",
        record: "31-20 (60.8%) last 52 weeks",
        style: "Aggressive flat hitter",
        strengths: "Forehand, serve, hard court game",
        serveStats: "Hold 70.9%, Ace 3.3%, DF 5.0% — above average DF rate",
        returnStats: "RPW 42.5%, Break rate 33.5% — below tour average",
        bpStats: "Break point conversion 48.4%, Save rate 55.2% — well below average",
        overallStats: "DR moderate, TPW ~51%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 · vs Gauff 0-0 · vs Pegula 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "BP save rate (55.2%) is well below tour average — she gets broken frequently when opponents get opportunities. Clay Elo #31 and grass Elo #23 show hard is clearly her best surface. Break rate (33.5%) is below tour average — her return game is not yet elite. Hard Elo #18 is the foundation of her game.",
        surfaceNote: { hard: "#18 hElo (1881.3) — hard is her best surface.", clay: "#31 cElo (1770.2) — below average on clay.", grass: "#23 gElo (1743.9) — modest grass game." }
      },
      "Mertens": {
        eloRank: 19, elo: 1914,
        hElo: 1860.5, hEloRank: 19, cElo: 1830.6, cEloRank: 15, gElo: 1765.5, gEloRank: 16, peakElo: 2042.7, peakMonth: "2021-04",
        yEloRank: 23, yElo2026: 1879.5, record2026: "10-5 — Solid form.",
        record: "32-20 (61.5%) last 52 weeks",
        style: "All-court consistent baseliner",
        strengths: "Consistency, return game, all-surface capability",
        serveStats: "Hold 73.5%, Ace 6.7%, DF 6.0% — above average DF rate",
        returnStats: "RPW 44.7%, Break rate 36.9% — above tour average",
        bpStats: "Break point conversion 45.7%, Save rate 59.1%",
        overallStats: "DR moderate, TPW ~52%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 · vs Gauff 0-0 · vs Pegula 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Clay Elo #15 (1830.6) — genuinely solid on clay. Hard Elo #19 and grass Elo #16 show she is one of the more multi-surface players outside the top 10. Return game is above average (36.9% break rate). A consistent, reliable player who rarely loses to lower-ranked opponents.",
        surfaceNote: { hard: "#19 hElo (1860.5) — solid on hard.", clay: "#15 cElo (1830.6) — strong on clay.", grass: "#16 gElo (1765.5) — capable on grass." }
      },
      "Cirstea": {
        eloRank: 20, elo: 1908,
        hElo: 1882.3, hEloRank: 17, cElo: 1764.0, cEloRank: 36, gElo: 1659.4, gEloRank: 54, peakElo: 1928.2, peakMonth: "2009-08",
        yEloRank: 8, yElo2026: 1941.4, record2026: "14-4 — #8 in-season form. Exceptional 2026 at 35.",
        record: "33-16 (67.3%) last 52 weeks",
        style: "Aggressive flat hitter",
        strengths: "Hard court game, serve, flat groundstrokes",
        serveStats: "Hold 75.8%, Ace 7.0%, DF 3.1% — low DF rate",
        returnStats: "RPW 44.0%, Break rate 35.3% — just below tour average",
        bpStats: "Break point conversion 47.6%, Save rate 57.5%",
        overallStats: "DR moderate, TPW ~52%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 · vs Gauff 0-0 · vs Pegula 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "At 35, her yElo #8 in 2026 (14-4) is genuinely remarkable. Hard Elo #17 (1882.3) is solid. Clay Elo #36 and grass Elo #54 show she is almost exclusively a hard court performer — fade her heavily on clay or grass. Low DF rate (3.1%) suggests controlled serving. Her career peak was back in 2009 — this 2026 resurgence is one of the best stories on tour.",
        surfaceNote: { hard: "#17 hElo (1882.3) — hard court specialist.", clay: "#36 cElo (1764.0) — significant clay weakness.", grass: "#54 gElo (1659.4) — avoid on grass." }
      },
      "Jovic": {
        eloRank: 21, elo: 1890,
        hElo: 1843.0, hEloRank: 21, cElo: 1727.9, cEloRank: 54, gElo: 1758.8, gEloRank: 17, peakElo: 1951.1, peakMonth: "2026-02",
        yEloRank: 25, yElo2026: 1875.9, record2026: "14-6 — Solid 2026 form.",
        record: "26-14 (65.0%) last 52 weeks",
        style: "Aggressive young baseliner",
        strengths: "Power, athleticism, return game",
        serveStats: "Hold 68.8%, Ace 2.9%, DF 3.3%",
        returnStats: "RPW 45.6%, Break rate 40.0% — well above tour average",
        bpStats: "Break point conversion 47.7%, Save rate 57.6% — below average",
        overallStats: "DR moderate, TPW ~51%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 · vs Gauff 0-0 (source: Tennis Abstract — very limited top-15 record)",
        fullNote: "At 18, her RPW (45.6%) and break rate (40.0%) are both well above tour average — her return game is already elite. Clay Elo #54 (1727.9) reveals a large surface gap — she is hard and grass oriented. Grass Elo #17 (1758.8) is her second-best surface ranking. BP save rate (57.6%) is below average — vulnerability when opponents get chances.",
        surfaceNote: { hard: "#21 hElo (1843.0) — hard is her best surface.", clay: "#54 cElo (1727.9) — significant clay weakness for her age.", grass: "#17 gElo (1758.8) — second best surface." }
      },
      "Alexandrova": {
        eloRank: 22, elo: 1881,
        hElo: 1818.5, hEloRank: 28, cElo: 1800.8, cEloRank: 23, gElo: 1777.0, gEloRank: 12, peakElo: 1977.2, peakMonth: "2020-02",
        yEloRank: 117, yElo2026: 1619.5, record2026: "4-7 — yElo #117 is alarming. Significant form slump in 2026.",
        record: "42-26 (61.8%) last 52 weeks",
        style: "Aggressive baseliner",
        strengths: "Serve, forehand, hard court game",
        serveStats: "Hold 73.3%, Ace 7.1%, DF 6.1% — high DF rate",
        returnStats: "RPW 45.1%, Break rate 38.6% — above tour average",
        bpStats: "Break point conversion 45.0%, Save rate 58.0% — below average",
        overallStats: "DR moderate, TPW ~52%, Tiebreak moderate",
        h2h: "vs Sabalenka 4-4 · vs Rybakina 3-3 · vs Swiatek 2-6 · vs Gauff 1-4 · vs Pegula 3-1 · vs Anisimova 2-2 · vs Svitolina 1-3 · vs Andreeva 0-4 · vs Bencic 1-0 · vs Noskova 0-1 (source: Tennis Abstract H2H matrix)",
        fullNote: "Grass Elo #12 (1777.0) is her best surface ranking — stronger on grass than her reputation suggests. yElo #117 in 2026 (4-7) is a major red flag — this is a player in serious current form decline despite her Elo rank. High DF rate (6.1%) and below-average BP save rate are structural weaknesses. Fade her at Miami based on 2026 form.",
        surfaceNote: { hard: "#28 hElo (1818.5) — below average in top 25 on hard.", clay: "#23 cElo (1800.8) — solid on clay.", grass: "#12 gElo (1777.0) — best surface. Underrated at Wimbledon." }
      },
      "Zheng": {
        eloRank: 24, elo: 1875,
        hElo: 1826.2, hEloRank: 25, cElo: 1843.2, cEloRank: 13, gElo: 1645.4, gEloRank: 65, peakElo: 2098.3, peakMonth: "2024-11",
        yEloRank: 0, yElo2026: 0, record2026: "Very limited — injury/schedule affected",
        record: "18-10 (64.3%) last 52 weeks",
        style: "Powerful all-court baseliner",
        strengths: "Forehand, athleticism, clay court game",
        serveStats: "Hold 71.7%, Ace 7.4%, DF 5.9% — above average DF rate",
        returnStats: "RPW 44.0%, Break rate 36.4% — above tour average",
        bpStats: "Break point conversion 48.7%, Save rate 55.9% — below average",
        overallStats: "DR moderate, TPW ~52%, Tiebreak moderate",
        h2h: "vs Sabalenka 0-0 · vs Rybakina 0-0 · vs Swiatek 0-0 · vs Gauff 0-0 (source: Tennis Abstract — limited top-15 record)",
        fullNote: "Clay Elo #13 (1843.2) is actually stronger than her hard Elo (#25, 1826.2) — she is fundamentally a clay court player. Grass Elo #65 (1645.4) is a dramatic weakness. She was at career peak (2098) in November 2024 — 223 points above current level. BP save rate (55.9%) is below average. Very limited 2026 match data makes assessment difficult.",
        surfaceNote: { hard: "#25 hElo (1826.2) — solid on hard.", clay: "#13 cElo (1843.2) — clay is her best surface.", grass: "#65 gElo (1645.4) — dramatic grass weakness. Avoid at Wimbledon." }
      },
      "Kartal": {
        eloRank: 25, elo: 1874,
        hElo: 1832.6, hEloRank: 24, cElo: 1602.3, cEloRank: 128, gElo: 1731.6, gEloRank: 27, peakElo: 1879.9, peakMonth: "2026-03",
        yEloRank: 19, yElo2026: 1891.7, record2026: "12-6 — #19 in-season form. Currently at career peak Elo.",
        record: "Unknown — rapidly rising",
        style: "Aggressive baseliner",
        strengths: "Hard court game, serve, athleticism",
        serveStats: "Limited data",
        returnStats: "Limited data",
        bpStats: "Limited data",
        overallStats: "Currently at career peak Elo (March 2026)",
        h2h: "vs top 15 — very limited record (source: Tennis Abstract)",
        fullNote: "British player currently at career peak Elo (1879.9 in March 2026). Clay Elo #128 (1602.3) is an enormous surface gap — she is almost exclusively a hard and grass court player. Grass Elo #27 (1731.6) is her second-best surface. yElo #19 confirms strong 2026 form. At WTA rank #56 she is significantly underrated by the official ranking system relative to her Elo.",
        surfaceNote: { hard: "#24 hElo (1832.6) — hard is her best surface.", clay: "#128 cElo (1602.3) — extreme clay weakness. Never back her on clay.", grass: "#27 gElo (1731.6) — second best surface." }
      },
    }
  });
}
